"""
Patient model.

Changes from original model.py:
- Inherits TenantMixin (adds tenant_id FK)
- REMOVED: first_name, middle_name, last_name, gender, dob, profile_image
           — these now live on User
- Added: full_name property that delegates to self.user.full_name
- All DateTime columns use timezone=True
"""
import uuid

from sqlalchemy import Index, event, text
from sqlalchemy.dialects.postgresql import UUID, JSON

from app.extensions import db
from app.models._base import TenantMixin, utcnow
from app.models._enums import BloodGroup


class Patient(TenantMixin, db.Model):
    """Patient profile extending the User model."""
    __tablename__ = 'patients'

    id = db.Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, name='patient_id')
    user_id = db.Column(
        UUID(as_uuid=True),
        db.ForeignKey('users.user_id', ondelete='CASCADE'),
        unique=True,
        nullable=False,
        index=True
    )

    # Health attributes (not personal-identity)
    blood_group = db.Column(db.Enum(BloodGroup), nullable=True)
    languages_known = db.Column(JSON, nullable=True)  # ["English", "Hindi"]

    # Statutory record identity, sealed at account deletion. Medical
    # records must stay identifiable for their retention period (NMC/MCI
    # reg. 1.3) even after the person's LOGIN identity is erased under
    # DPDP — so delete_account snapshots {full_name, first_name,
    # middle_name, last_name, gender, dob} here before anonymizing the
    # User row. Contact channels are never stored here. NULL for every
    # live account; ``full_name`` below falls back to it once set.
    record_identity = db.Column(JSON, nullable=True)

    # Emergency contact
    emergency_contact_name = db.Column(db.String(200), nullable=True)
    emergency_contact_phone = db.Column(db.String(15), nullable=True)
    emergency_contact_relation = db.Column(db.String(100), nullable=True)

    # Insurance
    insurance_provider = db.Column(db.String(200), nullable=True)
    insurance_policy_number = db.Column(db.String(100), nullable=True)

    # Extended Profile
    caste = db.Column(db.String(100), nullable=True)
    religion = db.Column(db.String(100), nullable=True)
    citizenship = db.Column(db.String(100), nullable=True)
    pan_number = db.Column(db.String(50), nullable=True)
    aadhar_number = db.Column(db.String(50), nullable=True)  # Masked or encrypted ideally

    alternative_phone = db.Column(db.String(20), nullable=True)
    alternative_email = db.Column(db.String(254), nullable=True)

    # Organization
    organization_details = db.Column(JSON, nullable=True)  # {type: 'individual'|'organization', name: '', id: ''}

    # Female Specific
    female_health_details = db.Column(JSON, nullable=True)  # {lmp_date: '', lmp_remarks: '', pregnancy_status: '', pregnancy_remarks: ''}

    # Address
    address_details = db.Column(JSON, nullable=True)  # {address_line1, address_line2, city, state, pincode, country}

    # Timestamps
    created_at = db.Column(db.DateTime(timezone=True), default=utcnow, nullable=False)
    updated_at = db.Column(db.DateTime(timezone=True), default=utcnow, onupdate=utcnow, nullable=False)

    # Soft delete
    is_deleted = db.Column(db.Boolean, default=False, nullable=False, index=True)
    deleted_at = db.Column(db.DateTime(timezone=True), nullable=True)

    # Round-10 followup — who invited this patient onto the tenant.
    # Populated by the invite flow (``_invite_patient_core``). NULL on
    # patients created via the public signup path (self-service) or
    # any pre-existing rows from before this column was added. Powers
    # the doctor's "My Patients" + admin's invitee-roster surfaces.
    #
    # FK + index names pinned explicitly so SQLAlchemy's
    # ``db.create_all()`` bootstrap (used by CI on empty DBs +
    # local test setup) produces the EXACT same identifiers as the
    # alembic migration. Without the explicit names the autogenerated
    # ``patients_invited_by_user_id_fkey`` mismatches the migration's
    # ``fk_patients_invited_by_user_id``, and the downgrade roundtrip
    # CI step fails with "constraint does not exist".
    invited_by_user_id = db.Column(
        UUID(as_uuid=True),
        db.ForeignKey(
            'users.user_id',
            ondelete='SET NULL',
            name='fk_patients_invited_by_user_id',
        ),
        nullable=True,
        index=True,
    )

    # ── Profile-change provenance ─────────────────────────────────────────
    # Who last changed anything on this patient's profile, and when. The
    # profile is editable from two places — the patient's own settings page
    # and the admin Operations act-on-behalf surface — so "updated_at" alone
    # can't answer the question support actually asks: *who* touched it.
    #
    # Distinct from ``updated_at``, which SQLAlchemy bumps on ANY column
    # write (including booking- and billing-side denormalisation), and from
    # ``OperationsAuditLog``, which only records admin actions. These three
    # columns are the cheap "latest state" read for the profile header;
    # the audit log remains the full history.
    #
    # ``profile_updated_by_role`` is a snapshot, not a join: it must keep
    # saying "an admin did this" even if that person's role changes later or
    # their user row is deleted (the FK is ON DELETE SET NULL).
    #
    # FK/index names pinned explicitly for the same reason as
    # ``invited_by_user_id`` above — db.create_all() and the alembic
    # migration have to produce identical identifiers.
    profile_updated_at = db.Column(db.DateTime(timezone=True), nullable=True)
    profile_updated_by_id = db.Column(
        UUID(as_uuid=True),
        db.ForeignKey(
            'users.user_id',
            ondelete='SET NULL',
            name='fk_patients_profile_updated_by_id',
        ),
        nullable=True,
        index=True,
    )
    profile_updated_by_role = db.Column(db.String(30), nullable=True)

    # Per-section provenance for accountability: a small map
    # ``{section_key: {by_id, by_role, at}}`` recording who last changed each
    # profile / health section (personal_details, vitals, insurance, …), so the
    # UI can show a "last updated by …" line under each — complementing the
    # whole-profile ``profile_updated_*`` above. Stamped by
    # ``profile_audit.stamp_section_update``.
    section_provenance = db.Column(JSON, nullable=True)

    # Relationships
    user = db.relationship(
        'User', back_populates='patient_profile',
        foreign_keys=[user_id],
    )
    invited_by = db.relationship(
        'User', foreign_keys=[invited_by_user_id],
    )
    profile_updated_by = db.relationship(
        'User', foreign_keys=[profile_updated_by_id],
    )
    appointments = db.relationship('Appointment', back_populates='patient', lazy='dynamic')
    prescriptions = db.relationship('Prescription', back_populates='patient', lazy='dynamic')
    doctor_documents = db.relationship('DoctorDocument', back_populates='patient', lazy='dynamic')
    health_records = db.relationship(
        'HealthRecord', back_populates='patient',
        cascade="all, delete-orphan", lazy='dynamic'
    )
    question_answers = db.relationship('PatientQuestionAnswer', back_populates='patient', lazy='dynamic')
    house_group = db.relationship(
        'HouseGroupMember', back_populates='patient',
        lazy='dynamic', cascade='all, delete-orphan',
        foreign_keys='[HouseGroupMember.patient_id]'
    )

    __table_args__ = (
        Index('ix_patients_active', 'tenant_id', postgresql_where=text('is_deleted = FALSE')),
    )

    @property
    def full_name(self):
        """Delegate to the linked User's full_name — unless the account
        was deleted, in which case the sealed ``record_identity`` keeps
        the retained medical record identifiable (the User row's name is
        anonymized to 'Deleted Account' at that point)."""
        if self.record_identity and self.record_identity.get('full_name'):
            return self.record_identity['full_name']
        if self.user:
            return self.user.full_name
        return ''

    def to_dict(self, include_user=False):
        data = {
            'id': str(self.id),
            'user_id': str(self.user_id),
            'full_name': self.full_name,
            # Personal info now sourced from User
            'first_name': self.user.first_name if self.user else None,
            'middle_name': self.user.middle_name if self.user else None,
            'last_name': self.user.last_name if self.user else None,
            'gender': self.user.gender.value if (self.user and self.user.gender) else None,
            'dob': self.user.dob.isoformat() if (self.user and self.user.dob) else None,
            'profile_image': self.user.profile_image if self.user else None,
            'blood_group': self.blood_group.value if self.blood_group else None,
            'languages_known': self.languages_known,
            # Extended profile fields
            'caste': self.caste,
            'religion': self.religion,
            'citizenship': self.citizenship,
            'pan_number': self.pan_number,
            'aadhar_number': self.aadhar_number,
            'alternative_phone': self.alternative_phone,
            'alternative_email': self.alternative_email,
            'organization_details': self.organization_details,
            'female_health_details': self.female_health_details,
            # Emergency contact
            'emergency_contact_name': self.emergency_contact_name,
            'emergency_contact_phone': self.emergency_contact_phone,
            'emergency_contact_relation': self.emergency_contact_relation,
            # Insurance
            'insurance_provider': self.insurance_provider,
            'insurance_policy_number': self.insurance_policy_number,
        }
        # Include phone/email from User model
        if self.user:
            data['phone_number'] = self.user.phone_number
            data['email'] = self.user.email
        if include_user and self.user:
            data['user_details'] = self.user.to_dict()
        return data


@event.listens_for(Patient, 'before_insert')
def _seed_profile_provenance(_mapper, _connection, target):
    """Creating a profile counts as its first update.

    Without this, a brand-new patient reads "no update recorded" until someone
    edits them, which is both unhelpful and untrue — the profile *was* written,
    by someone, at a known moment.

    A mapper event rather than a call in each constructor: patients are created
    from five places today (self-signup, admin invite, affiliation, public
    booking, ``PatientService.create_profile``) and a sixth would silently miss
    the stamp.

    Actor resolution:
    * an admin creating the profile (invite / affiliation flows) is credited —
      :func:`current_actor` returns them;
    * self-signup and public booking have no authenticated actor yet, so the
      patient is credited with their own creation, which is what happened.
    """
    from app.common.profile_audit import current_actor
    from app.models._enums import UserRole

    if target.profile_updated_at is not None:
        return  # caller set it explicitly — don't second-guess

    actor = current_actor()
    target.profile_updated_at = utcnow()
    if actor is not None and str(getattr(actor, 'id', '')) != str(target.user_id):
        target.profile_updated_by_id = actor.id
        target.profile_updated_by_role = (
            actor.role.value if getattr(actor, 'role', None) else None
        )
    else:
        # ``user_id`` is enough — no query, and the User row may still be
        # pending in this same flush.
        target.profile_updated_by_id = target.user_id
        target.profile_updated_by_role = UserRole.PATIENT.value

    def __repr__(self):
        return f"<Patient {self.full_name}>"
