"""Database migration bootstrap.

Single entrypoint the deploy pipeline calls. Handles both:

  * **First-time deploy** (no ``alembic_version`` table yet)
    - calls ``db.create_all()`` to materialise the entire current schema
      (SQLAlchemy handles FK topological ordering correctly).
    - stamps the DB at the latest Alembic revision so future deploys
      apply only incremental migrations.

  * **Subsequent deploys** (``alembic_version`` already exists)
    - prunes redundant ``alembic_version`` rows (see
      ``prune_redundant_versions``) so a rewritten ``down_revision``
      can't wedge the deploy.
    - runs ``flask db upgrade`` which applies every migration committed
      since the last deploy. Safe to re-run; alembic skips already-applied
      revisions.

This pattern is the standard recipe for retrofitting Alembic onto an
existing project. It avoids the FK-ordering pitfalls of an autogenerated
``op.create_table`` baseline for ~50 interlinked tables, while still
giving us versioned, incremental schema delivery for every model change
from this commit onward.

Usage:
    docker run … --entrypoint python <image> scripts/migrate.py
"""
import logging
import os
import sys

# When run as ``python scripts/migrate.py`` the script's own dir is on
# sys.path but the parent (which contains ``app/``, ``wsgi.py``, etc.)
# is not. Add it so ``from app import …`` works regardless of cwd.
_PARENT = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
if _PARENT not in sys.path:
    sys.path.insert(0, _PARENT)

from sqlalchemy import text
from flask_migrate import stamp, upgrade

logging.basicConfig(level=logging.INFO, format='%(asctime)s [migrate] %(message)s')
log = logging.getLogger(__name__)


def has_alembic_version_table(db) -> bool:
    """True if the ``alembic_version`` table exists in the connected DB."""
    result = db.session.execute(text("SELECT to_regclass('public.alembic_version')"))
    return result.scalar() is not None


def _parents(revision) -> tuple:
    """Every immediate ancestor of ``revision`` — ``down_revision`` + deps.

    Both attributes are ``None`` / ``str`` / tuple-of-str depending on
    whether the migration is a base, a normal one, or a merge.
    """
    ids = []
    for attr in (revision.down_revision, revision.dependencies):
        if not attr:
            continue
        ids.extend((attr,) if isinstance(attr, str) else tuple(attr))
    return tuple(ids)


def _ancestors(script, revision) -> set:
    """All transitive ancestors of ``revision`` (excluding itself)."""
    seen: set = set()
    todo = [revision]
    while todo:
        for parent_id in _parents(todo.pop()):
            if parent_id in seen:
                continue
            seen.add(parent_id)
            parent = script.get_revision(parent_id)
            if parent is not None:
                todo.append(parent)
    return seen


def prune_redundant_versions(db) -> None:
    """Drop ``alembic_version`` rows that are ancestors of another row.

    ``alembic_version`` legitimately holds several rows while the graph has
    several heads. But if a migration's ``down_revision`` is later rewritten
    to point at a revision the DB already recorded as a co-head, those two
    rows stop being independent — one becomes an ancestor of the other — and
    alembic refuses to move at all::

        Error: Requested revision <child> overlaps with other requested
        revisions <ancestor>

    (it raises this while walking the *stored* revisions, which is why the
    message names rows in the table rather than anything in this deploy).
    The ancestor row carries no information the child row doesn't already
    imply, so deleting it is lossless and unwedges the upgrade.

    Rows unknown to this deploy's ``migrations/versions`` are left alone —
    they mean the DB is ahead of the code, which is not ours to resolve.
    """
    from flask import current_app
    from alembic.script import ScriptDirectory

    rows = [r[0] for r in db.session.execute(text('SELECT version_num FROM alembic_version'))]
    if len(rows) < 2:
        return

    script = ScriptDirectory.from_config(current_app.extensions['migrate'].migrate.get_config())

    revisions = {}
    for row in rows:
        try:
            revisions[row] = script.get_revision(row)
        except Exception:  # ResolutionError — revision not in this build
            log.warning('alembic_version row %s is unknown to this build; leaving it', row)

    ancestors = {rev_id: _ancestors(script, rev) for rev_id, rev in revisions.items()}
    redundant = sorted(
        rev_id for rev_id in revisions
        if any(rev_id in other for key, other in ancestors.items() if key != rev_id)
    )
    if not redundant:
        return

    log.info(
        'alembic_version has %d rows (%s); dropping %d now-redundant ancestor row(s): %s',
        len(rows), ', '.join(rows), len(redundant), ', '.join(redundant),
    )
    for rev_id in redundant:
        db.session.execute(
            text('DELETE FROM alembic_version WHERE version_num = :rev'), {'rev': rev_id}
        )
    db.session.commit()


def main() -> int:
    # Imported lazily so this script can be loaded by tools that don't
    # have Flask creds set yet (e.g. ``python -c "import scripts.migrate"``).
    from app import create_app
    from app.extensions import db

    app = create_app()
    with app.app_context():
        if not has_alembic_version_table(db):
            log.info('first-time bootstrap: creating schema via db.create_all()')
            db.create_all()
            # ``heads`` (plural) not ``head`` — a fresh create_all() built the
            # full current schema, so stamping ALL alembic heads is correct and
            # keeps bootstrap resilient when parallel branches leave the graph
            # with more than one head (they get merged later via a merge
            # migration; a deploy must not fail in the meantime).
            log.info('stamping DB at latest alembic revision(s)')
            stamp(revision='heads')
            log.info('bootstrap complete — DB is at head(s)')
        else:
            log.info('existing DB detected — running flask db upgrade')
            prune_redundant_versions(db)
            # ``heads`` applies every pending migration across all head
            # branches, so an unmerged parallel migration never blocks a deploy.
            upgrade(revision='heads')
            log.info('upgrade complete — DB is at head(s)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
