import { createApi } from '@reduxjs/toolkit/query/react';
import axiosBaseQuery from './axiosBaseQuery';

/**
 * Global API Slice
 * precise centralized RTK Query configuration.
 * All feature endpoints should inject into this slice.
 */
export const apiSlice = createApi({
    reducerPath: 'api',
    baseQuery: axiosBaseQuery({ baseUrl: '' }),
  tagTypes: [
  // New-look pages — endpoints ASSUMED, backend not implemented yet (see
  // features/service-receiver/newlook/api/assumedEndpoints.js for the table).
  'NLWallet',
  'NLNotification',
  'NLRecoveryPlan',
  'Admin',
  'Patient',
  'Doctor',
  'Appointment',
  'PageConfig',
  'DoctorProfileConfig',
  'DoctorSignupConfig',
  'MasterDegree',
  'PatientProfileConfig',
  'AdminProfileConfig',
  'AdminProfile',
  'DoctorAnalytics',
  'DoctorAttendance',
  'MasterCollege',
  'MasterSpecialization',
  'Product',
  'FeatureProductLink',
  'AvailabilityApproval',
  'MarketplaceProduct',
  'MarketplaceOrder',
  'AppointmentDocument',
  'FieldApproval',
  'AccountStatus',
  'FacilityProfile',
  'SlotVisibilityApproval',
  'DoctorAdminRequest',
  'HealthRecord',
  'Vitals',
  'Habits',
  'HouseGroupRequest',
  'HouseGroup',
  // Provenance for the patient-profile header ("Last updated on X by …").
  // Every profile mutation invalidates it via `invalidatesProfile` so a save
  // in any tab refreshes the indicator.
  'ProfileAudit',
  'SlotAvailability',
  'MedicalContext',
  'AppointmentPrescriptions',
  'PatientSpending',
  'HealthCredits',
  'DoctorSymptoms',
  'PatientAppointmentConfig',
  'Billing',
  'BillingConfig',
  'DisplayPricing',
  'TaxConfig',
  'Payout',
  'LandingConfig',
  'LandingModule',
  'LandingFeature',
  'LandingSnapshot',
  'LandingRecognition',
  'LandingVideo',
  'LandingDoctor',
  'LandingReview',
  'LandingTrustedBrand',
  'PlatformTenant',
  'TenantPermissions',
  'TenantAdmins',
  'Plan',
  'PlanType',
  'VerticalType',
  'Addon',
  'MyPlan',
  'TenantSubscription',
  'TenantAddons',
  'MembershipPlan',
  'MembershipSubscription',
  'CreditPolicy',
  'ChargePolicy',
  'ApprovalPolicy',
  'ServiceInterest',
  // Service Communication — must be listed here or invalidatesTags silently
  // no-ops (the bug 'Prescription' still has: used throughout
  // doctorEndpoints.js but absent from this array).
  'ServiceCommunicationConfig',
  'ServiceChannel',
  'ChannelMessages',
  'ChannelCalls',
  'ChannelDocuments',
  'ChannelForms',
  'ChannelTimeline',
  'MyMembership',
  'PlatformLanding',
  'PlatformLandingModule',
  'PlatformLandingFeature',
  'PlatformLandingHistory',
  'PlatformLandingRecognition',
  'PlatformLandingVideo',
  'PublicBookingSpecialization',
  'PublicBookingDoctor',
  'PublicBookingSlot',
  'AffiliationInvite',
  'AffiliationRequest',
  'FacilityRoster',
  'OpsPatient',
  'OpsBooking',
  // Provider-staff RBAC (Operations → Manage Roles & Permissions)
  'ProviderModules',
  'ProviderRole',
  'ProviderRolePerms',
  'ProviderStaff',
  // The provider's own view of the same rows (My Link → Support Staff)
  'MyStaff',
  'MyStaffRoles',
  'MyStaffRolePerms',
  'MyStaffModules',
  // A signed-in staff member's own profile + effective permissions
  'StaffMe',
  'CareNetworkConnection',
  'CareNetworkRequest',
  'ServiceGroup',
  'PlanBooking',
  'HeldVendors',
  'AdminServiceGroup',
  'AdminMarketplaceProduct',
  'AdminGroupOffering',
  'GroupOfferingPlan',
  'GroupOfferingBooking',
  'GroupOfferingPayout',
  'OrderPayout',
  'GroupOfferingTeam',
  'ProviderVisibility',
  'DoctorBilling',
  'SalaryPayout',
  'WorkQualification',
  'Document',
  'DocumentApprovals',
  // Patient Family — minor sub-profiles, switch-into scopes, and reciprocal
  // roles. Must be listed or invalidatesTags silently no-ops (see the
  // Service Communication note above).
  'FamilyMinor',
  'FamilyScope',
  'FamilyRole',
  // Admin: per-plan Patient Family quotas (minors / links / roles).
  'PatientFamilyPolicy',
  // Patient support staff (caregiver seats) + the caregiver's own /me.
  'PatientStaff',
  'PatientStaffMe',
  // Clinic branches (a main clinic's login-less sub-clinics).
  'ClinicBranch'
],
  endpoints: () => ({}),
});
