import { createApi } from '@reduxjs/toolkit/query/react';
import axiosBaseQuery from './axiosBaseQuery';

/**
 * Global API Slice
 * precise centralized RTK Query configuration.
 * All feature endpoints should inject into this slice.
 */
export const apiSlice = createApi({
    reducerPath: 'api',
    baseQuery: axiosBaseQuery({ baseUrl: '' }),
  tagTypes: [
  'SupportThread',
  'SupportInbox',
  'Admin',
  'Patient',
  'Doctor',
  'Appointment',
  'PageConfig',
  'DoctorProfileConfig',
  'DoctorSignupConfig',
  'MasterDegree',
  'PatientProfileConfig',
  'AdminProfileConfig',
  'AdminProfile',
  'DoctorAnalytics',
  'DoctorAttendance',
  'MasterCollege',
  'MasterSpecialization',
  'Product',
  'ProductCategory',
  'FeatureProductLink',
  'AvailabilityApproval',
  'MarketplaceProduct',
  'MarketplaceOrder',
  'AppointmentDocument',
  'FieldApproval',
  'AccountStatus',
  'FacilityProfile',
  'SlotVisibilityApproval',
  'DoctorAdminRequest',
  'HealthRecord',
  'Vitals',
  'Habits',
  'HouseGroupRequest',
  'HouseGroup',
  // Provenance for the patient-profile header ("Last updated on X by …").
  // Every profile mutation invalidates it via `invalidatesProfile` so a save
  // in any tab refreshes the indicator.
  'ProfileAudit',
  'SlotAvailability',
  'MedicalContext',
  'AppointmentPrescriptions',
  'PatientSpending',
  'HealthCredits',
  'DoctorSymptoms',
  'PatientAppointmentConfig',
  'Billing',
  'BillingConfig',
  'DisplayPricing',
  'TaxConfig',
  'Payout',
  'LandingConfig',
  'LandingModule',
  'LandingFeature',
  'LandingSnapshot',
  'LandingRecognition',
  'LandingVideo',
  'LandingDoctor',
  'LandingReview',
  'LandingTrustedBrand',
  'PlatformTenant',
  'TenantPermissions',
  'TenantAdmins',
  // A tenant's own routing (subdomain / custom domain / DNS / SSL) and
  // the first-run onboarding checklist derived from it.
  'TenantDomain',
  // The tenant's own SaaS subscription billing (pay / renew, history).
  'SaasBilling',
  // Per-user in-app notification feed (bell badge + list).
  'Notifications',
  // The tenant's own payment gateway (Razorpay collection + Cashfree
  // payout credentials) and DLT/SMS configuration.
  'TenantGateway',
  'TenantSmsConfig',
  'TenantEmailConfig',
  'Plan',
  'PlanType',
  'SaasCategory',
  'ResellerTenant',
  'ResellerQuota',
  'ResaleLedger',
  'ResellerDns',
  'VerticalType',
  'Addon',
  'MyPlan',
  'TenantSubscription',
  'TenantAddons',
  'MembershipPlan',
  'MembershipSubscription',
  'CreditPolicy',
  'ChargePolicy',
  'ApprovalPolicy',
  'ServiceInterest',
  // A tag must be listed here or its invalidatesTags silently no-op.
  // 'Prescription' / 'PatientPrescriptions' were exactly that bug (used
  // throughout doctorEndpoints.js / patientEndpoints.js but absent) —
  // registered now so prescription pushes live-refresh both sides.
  'Prescription',
  'PatientPrescriptions',
  'ServiceCommunicationConfig',
  'ServiceChannel',
  'ChannelMessages',
  'ChannelCalls',
  'ChannelDocuments',
  'ChannelForms',
  'ChannelTimeline',
  'MyMembership',
  'PlatformLanding',
  'PlatformLandingModule',
  'PlatformLandingFeature',
  'PlatformLandingHistory',
  'PlatformLandingRecognition',
  'PlatformLandingVideo',
  'PublicBookingSpecialization',
  'PublicBookingDoctor',
  'PublicBookingSlot',
  'AffiliationInvite',
  'AffiliationRequest',
  'FacilityRoster',
  'OpsPatient',
  'OpsBooking',
  // Provider-staff RBAC (Operations → Manage Roles & Permissions)
  'ProviderModules',
  'ProviderRole',
  'ProviderRolePerms',
  'ProviderStaff',
  // The provider's own view of the same rows (My Link → Support Staff)
  'MyStaff',
  'MyStaffRoles',
  'MyStaffRolePerms',
  'MyStaffModules',
  // A signed-in staff member's own profile + effective permissions
  'StaffMe',
  'CareNetworkConnection',
  'CareNetworkRequest',
  'ServiceGroup',
  'PlanBooking',
  'HeldVendors',
  'AdminServiceGroup',
  'AdminMarketplaceProduct',
  'AdminGroupOffering',
  'GroupOfferingPlan',
  'GroupOfferingBooking',
  'GroupOfferingPayout',
  'OrderPayout',
  'GroupOfferingTeam',
  'ProviderVisibility',
  'DoctorBilling',
  'SalaryPayout',
  'WorkQualification',
  'Document',
  'DocumentApprovals',
  // Patient Family — minor sub-profiles, switch-into scopes, and reciprocal
  // roles. Must be listed or invalidatesTags silently no-ops (see the
  // Service Communication note above).
  'FamilyMinor',
  'FamilyScope',
  'FamilyRole',
  // Admin: per-plan Patient Family quotas (minors / links / roles).
  'PatientFamilyPolicy',
  // Patient support staff (caregiver seats) + the caregiver's own /me.
  'PatientStaff',
  'PatientStaffMe',
  // Clinic branches (a main clinic's login-less sub-clinics).
  'ClinicBranch'
],
  endpoints: () => ({}),
});
