"""feature whats_included

Revision ID: 002ef9ae392a
Revises: f93fb6c8413d
Create Date: 2026-07-25 07:29:58.590205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002ef9ae392a'
down_revision = 'f93fb6c8413d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landing_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whats_included', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('platform_landing_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whats_included', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_landing_features', schema=None) as batch_op:
        batch_op.drop_column('whats_included')

    with op.batch_alter_table('landing_features', schema=None) as batch_op:
        batch_op.drop_column('whats_included')

    # ### end Alembic commands ###
