"""credit_policy second_opinion percentage

Revision ID: 038699102e33
Revises: 544e7dc41084
Create Date: 2026-08-07 13:49:22.865664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '038699102e33'
down_revision = '544e7dc41084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_opinion_pct', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('second_opinion_pcts', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_policies', schema=None) as batch_op:
        batch_op.drop_column('second_opinion_pcts')
        batch_op.drop_column('second_opinion_pct')

    # ### end Alembic commands ###
