"""salary payout lifecycle columns

Gives SalaryPayout the same lifecycle as DoctorPayout (hold → push → claim →
transfer) plus the amount fields the adjustment/incentive work builds on.

Two hand-edits to the autogenerated output, both needed for production:

  * ``adjustments_total`` / ``incentive_total`` are NOT NULL, so they carry a
    ``server_default`` of 0. Without it the ALTER fails the moment the table has
    any row — our dev DB is empty, so this would have passed locally and broken
    on a real deploy.
  * The foreign keys are named. Alembic emitted ``create_foreign_key(None, …)``,
    and the matching ``drop_constraint(None, …)`` cannot execute — an unnamed
    constraint is not droppable, so the downgrade was broken as generated.

Revision ID: 0389f9e1d9d3
Revises: vpt1tenant2scope3
Create Date: 2026-07-20 23:17:45.152221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0389f9e1d9d3'
down_revision = 'vpt1tenant2scope3'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('salary_payouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'adjustments_total', sa.Numeric(precision=10, scale=2),
            nullable=False, server_default='0',
        ))
        batch_op.add_column(sa.Column(
            'incentive_total', sa.Numeric(precision=10, scale=2),
            nullable=False, server_default='0',
        ))
        batch_op.add_column(sa.Column('bank_account_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('hold_until', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('payout_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('claim_requested_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('claimed_by_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('razorpay_transfer_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_salary_payouts_hold_until'), ['hold_until'], unique=False)
        batch_op.create_foreign_key(
            'fk_salary_payouts_bank_account', 'profile_bank_accounts',
            ['bank_account_id'], ['id'], ondelete='SET NULL',
        )
        batch_op.create_foreign_key(
            'fk_salary_payouts_claimed_by', 'users',
            ['claimed_by_id'], ['user_id'], ondelete='SET NULL',
        )


def downgrade():
    with op.batch_alter_table('salary_payouts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_salary_payouts_claimed_by', type_='foreignkey')
        batch_op.drop_constraint('fk_salary_payouts_bank_account', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_salary_payouts_hold_until'))
        batch_op.drop_column('razorpay_transfer_id')
        batch_op.drop_column('claimed_by_id')
        batch_op.drop_column('claim_requested_at')
        batch_op.drop_column('payout_mode')
        batch_op.drop_column('hold_until')
        batch_op.drop_column('bank_account_id')
        batch_op.drop_column('incentive_total')
        batch_op.drop_column('adjustments_total')
