"""unify group offering docs into doctor_documents

Revision ID: 100b76298191
Revises: cf55b5b2573a
Create Date: 2026-07-26 10:31:33.872983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '100b76298191'
down_revision = 'cf55b5b2573a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_offering_booking_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_offering_booking_documents_booking_id'))
        batch_op.drop_index(batch_op.f('ix_group_offering_booking_documents_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_group_offering_booking_documents_tenant_id'))

    op.drop_table('group_offering_booking_documents')
    with op.batch_alter_table('doctor_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_booking_id', sa.UUID(), nullable=True))
        batch_op.alter_column('order_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_doctor_documents_group_booking_id'), ['group_booking_id'], unique=False)
        batch_op.create_foreign_key('doctor_documents_group_booking_id_fkey', 'group_offering_bookings', ['group_booking_id'], ['booking_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_documents', schema=None) as batch_op:
        batch_op.drop_constraint('doctor_documents_group_booking_id_fkey', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_doctor_documents_group_booking_id'))
        batch_op.alter_column('order_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('group_booking_id')

    op.create_table('group_offering_booking_documents',
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('doctor_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('document_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('s3_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('s3_bucket', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['group_offering_bookings.booking_id'], name=op.f('group_offering_booking_documents_booking_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], name=op.f('group_offering_booking_documents_doctor_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('group_offering_booking_documents_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', name=op.f('group_offering_booking_documents_pkey'))
    )
    with op.batch_alter_table('group_offering_booking_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_offering_booking_documents_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_booking_documents_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_booking_documents_booking_id'), ['booking_id'], unique=False)

    # ### end Alembic commands ###
