"""clinic branches: parent_clinic_id + staff branch scopes

Revision ID: 19aad26cfcdc
Revises: 2b05969c21a3
Create Date: 2026-08-10 12:47:26.577320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19aad26cfcdc'
down_revision = '2b05969c21a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_staff_branch_scopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('granted_by_id', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['provider_staff.staff_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'clinic_id', name='uq_provider_staff_branch')
    )
    with op.batch_alter_table('provider_staff_branch_scopes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_staff_branch_scopes_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_staff_branch_scopes_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_staff_branch_scopes_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_clinic_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_clinics_parent_clinic_id'), ['parent_clinic_id'], unique=False)
        batch_op.create_foreign_key('fk_clinics_parent_clinic_id', 'clinics', ['parent_clinic_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clinics_parent_clinic_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_clinics_parent_clinic_id'))
        batch_op.drop_column('parent_clinic_id')

    with op.batch_alter_table('provider_staff_branch_scopes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_staff_branch_scopes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_provider_staff_branch_scopes_staff_id'))
        batch_op.drop_index(batch_op.f('ix_provider_staff_branch_scopes_clinic_id'))

    op.drop_table('provider_staff_branch_scopes')
    # ### end Alembic commands ###
