"""user is_managed flag for guardian-owned minor profiles

Revision ID: 1a543f48bb1a
Revises: a1288160ece1
Create Date: 2026-08-09 09:16:28.530550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a543f48bb1a'
down_revision = 'a1288160ece1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_managed', sa.Boolean(), server_default='false', nullable=False))
        batch_op.create_index(batch_op.f('ix_users_is_managed'), ['is_managed'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_managed'))
        batch_op.drop_column('is_managed')

    # ### end Alembic commands ###
