"""add sort_order to vertical_plan_types

Revision ID: 1c3a6b40eb08
Revises: c43e90233131
Create Date: 2026-07-19 07:42:51.416797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3a6b40eb08'
down_revision = 'c43e90233131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vertical_plan_types', schema=None) as batch_op:
        # server_default backfills the existing rows (NOT NULL); dropped
        # after so future inserts supply the value via the model.
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False,
                                      server_default='0'))
        batch_op.alter_column('sort_order', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vertical_plan_types', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
