"""Add pricing time period stuff and is_additional

Revision ID: 236d70d5180c
Revises: b4o5p6q7r8s9
Create Date: 2026-07-14 12:04:28.200864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '236d70d5180c'
down_revision = 'b4o5p6q7r8s9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addons', schema=None) as batch_op:
        batch_op.alter_column('features',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
        batch_op.alter_column('limits',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('usage_deltas',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('prerequisites',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('landing_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vid_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('img_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('landing_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vid_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('img_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vertical', sa.Enum('DOCTOR', 'CLINIC', 'HOSPITAL', name='membershipvertical'), nullable=True))
        batch_op.add_column(sa.Column('pricing', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('features',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
        batch_op.alter_column('usage_limits',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('default_addons',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_plans_vertical'), ['vertical'], unique=False)

    with op.batch_alter_table('platform_landing_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vid_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('img_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('platform_landing_modules', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_additional", sa.Boolean(), server_default=sa.text("false"), nullable=False
            )
        )
        batch_op.add_column(sa.Column('vid_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('img_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('tenant_subscriptions', schema=None) as batch_op:
        batch_op.alter_column('overrides',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_subscriptions', schema=None) as batch_op:
        batch_op.alter_column('overrides',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('platform_landing_modules', schema=None) as batch_op:
        batch_op.drop_column('img_json')
        batch_op.drop_column('vid_json')
        batch_op.drop_column('is_additional')

    with op.batch_alter_table('platform_landing_features', schema=None) as batch_op:
        batch_op.drop_column('img_json')
        batch_op.drop_column('vid_json')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_vertical'))
        batch_op.alter_column('default_addons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('usage_limits',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
        batch_op.drop_column('pricing')
        batch_op.drop_column('vertical')

    with op.batch_alter_table('landing_modules', schema=None) as batch_op:
        batch_op.drop_column('img_json')
        batch_op.drop_column('vid_json')

    with op.batch_alter_table('landing_features', schema=None) as batch_op:
        batch_op.drop_column('img_json')
        batch_op.drop_column('vid_json')

    with op.batch_alter_table('addons', schema=None) as batch_op:
        batch_op.alter_column('prerequisites',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('usage_deltas',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('limits',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)

    # ### end Alembic commands ###
