"""plan snapshot on subscriptions + plan audit log

Scoped by hand to ONLY this feature: alembic autogenerate also detected
unrelated local model/DB drift (group_offerings.product_category,
saas_categories index churn) which was stripped — it belongs to whichever
change introduced it, not here.

Revision ID: 24fcfa1cc769
Revises: temail1_tenant_email_configs
Create Date: 2026-08-20 20:14:06.776758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24fcfa1cc769'
down_revision = 'temail1_tenant_email_configs'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('plan_code', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('changes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_audit_logs_plan_code'), ['plan_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_audit_logs_plan_id'), ['plan_id'], unique=False)


    with op.batch_alter_table('tenant_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_subscriptions', schema=None) as batch_op:
        batch_op.drop_column('plan_snapshot')


    with op.batch_alter_table('plan_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_audit_logs_plan_id'))
        batch_op.drop_index(batch_op.f('ix_plan_audit_logs_plan_code'))
        batch_op.drop_index(batch_op.f('ix_plan_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_plan_audit_logs_actor_id'))

    op.drop_table('plan_audit_logs')
    # ### end Alembic commands ###
