"""Add periodic membership column

Revision ID: 25fd9e599be5
Revises: s5f6g7h8i9j0
Create Date: 2026-07-12 11:24:05.716078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25fd9e599be5'
down_revision = 's5f6g7h8i9j0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricing', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.drop_column('pricing')

    # ### end Alembic commands ###
