"""patient support staff seat + roles

Revision ID: 2b05969c21a3
Revises: 6167bbe6bd4a
Create Date: 2026-08-10 09:08:25.778866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b05969c21a3'
down_revision = '6167bbe6bd4a'
branch_labels = None
depends_on = None


def upgrade():
    # The caregiver login role. Autogenerate never detects enum additions, and
    # ALTER TYPE ... ADD VALUE can't run inside Alembic's transaction — hence
    # the autocommit block. IF NOT EXISTS keeps a re-run safe. (No RLS on the
    # new tables: their siblings provider_staff / patient_roles carry none, and
    # adding it here would diverge tenant handling from what they rely on.)
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'PATIENT_STAFF'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_staff',
    sa.Column('patient_staff_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('relation', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='patientstaffstatus'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('patient_staff_id')
    )
    with op.batch_alter_table('patient_staff', schema=None) as batch_op:
        batch_op.create_index('ix_patient_staff_active', ['tenant_id', 'patient_id', 'status'], unique=False, postgresql_where=sa.text('is_deleted = FALSE'))
        batch_op.create_index(batch_op.f('ix_patient_staff_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_staff_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_staff_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_staff_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_staff_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_staff_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_staff_user_id'), ['user_id'], unique=True)

    op.create_table('patient_staff_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['patient_roles.patient_role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['patient_staff.patient_staff_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'role_id', name='uq_patient_staff_role')
    )
    with op.batch_alter_table('patient_staff_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_staff_roles_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_staff_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_staff_roles_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_staff_roles_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_staff_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_staff_roles_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_patient_staff_roles_staff_id'))
        batch_op.drop_index(batch_op.f('ix_patient_staff_roles_role_id'))
        batch_op.drop_index(batch_op.f('ix_patient_staff_roles_is_active'))

    op.drop_table('patient_staff_roles')
    with op.batch_alter_table('patient_staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_staff_user_id'))
        batch_op.drop_index(batch_op.f('ix_patient_staff_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_patient_staff_status'))
        batch_op.drop_index(batch_op.f('ix_patient_staff_phone_number'))
        batch_op.drop_index(batch_op.f('ix_patient_staff_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_staff_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_patient_staff_email'))
        batch_op.drop_index('ix_patient_staff_active', postgresql_where=sa.text('is_deleted = FALSE'))

    op.drop_table('patient_staff')
    # ### end Alembic commands ###
    # The patient_staff table owned the patientstaffstatus enum type; drop it so
    # a re-upgrade recreates it cleanly. PATIENT_STAFF stays on ``userrole`` —
    # Postgres cannot drop an enum value, and any staff User row would still
    # reference it.
    op.execute('DROP TYPE IF EXISTS patientstaffstatus')
