"""prescription doctor credential snapshot

Revision ID: 2fe35abefa01
Revises: 3dcfcac922f5
Create Date: 2026-07-22 14:04:21.754323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe35abefa01'
down_revision = '3dcfcac922f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_qualification_snapshot', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('doctor_specialization_snapshot', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_column('doctor_specialization_snapshot')
        batch_op.drop_column('doctor_qualification_snapshot')

    # ### end Alembic commands ###
