"""drop dead group offering + order payout ledgers

Revision ID: 3118c02f008a
Revises: 85a556bd17cb
Create Date: 2026-07-26 08:58:46.862772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3118c02f008a'
down_revision = '85a556bd17cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_offering_payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_offering_payouts_booking_id'))
        batch_op.drop_index(batch_op.f('ix_group_offering_payouts_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_group_offering_payouts_status'))
        batch_op.drop_index(batch_op.f('ix_group_offering_payouts_tenant_id'))

    op.drop_table('group_offering_payouts')
    with op.batch_alter_table('marketplace_order_payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_order_payouts_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_order_payouts_order_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_order_payouts_status'))
        batch_op.drop_index(batch_op.f('ix_marketplace_order_payouts_tenant_id'))

    op.drop_table('marketplace_order_payouts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_order_payouts',
    sa.Column('payout_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('doctor_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('gross_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('gst_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('tds_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('net_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], name=op.f('marketplace_order_payouts_doctor_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['marketplace_orders.order_id'], name=op.f('marketplace_order_payouts_order_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('marketplace_order_payouts_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payout_id', name=op.f('marketplace_order_payouts_pkey'))
    )
    with op.batch_alter_table('marketplace_order_payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_order_payouts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_order_payouts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_order_payouts_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_order_payouts_doctor_id'), ['doctor_id'], unique=False)

    op.create_table('group_offering_payouts',
    sa.Column('payout_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('doctor_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('qualification_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('gross_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('gst_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('tds_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('net_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['group_offering_bookings.booking_id'], name=op.f('group_offering_payouts_booking_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], name=op.f('group_offering_payouts_doctor_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('group_offering_payouts_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payout_id', name=op.f('group_offering_payouts_pkey'))
    )
    with op.batch_alter_table('group_offering_payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_offering_payouts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_payouts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_payouts_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_payouts_booking_id'), ['booking_id'], unique=False)

    # ### end Alembic commands ###
