"""group offering patient bookings + installment payments

Revision ID: 397d99545c6f
Revises: gopay1sched2tax3
Create Date: 2026-07-25 20:49:57.824737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397d99545c6f'
down_revision = 'gopay1sched2tax3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_offering_bookings',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(length=200), nullable=True),
    sa.Column('plan_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_mode', sa.String(length=20), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_payable', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['group_offerings.group_offering_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id')
    )
    with op.batch_alter_table('group_offering_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_offering_bookings_offering_id'), ['offering_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_bookings_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_bookings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('group_offering_booking_installments',
    sa.Column('booking_installment_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_after_days', sa.Integer(), nullable=False),
    sa.Column('due_label', sa.String(length=50), nullable=True),
    sa.Column('is_booking', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['group_offering_bookings.booking_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_installment_id')
    )
    with op.batch_alter_table('group_offering_booking_installments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_offering_booking_installments_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_booking_installments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_booking_installments_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('group_offering_installments', schema=None) as batch_op:
        batch_op.create_foreign_key('group_offering_installments_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_installment_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_booking_installment_id'), ['booking_installment_id'], unique=False)
        batch_op.create_foreign_key('payments_booking_installment_id_fkey', 'group_offering_booking_installments', ['booking_installment_id'], ['booking_installment_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('payments_booking_installment_id_fkey', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_booking_installment_id'))
        batch_op.drop_column('booking_installment_id')

    with op.batch_alter_table('group_offering_installments', schema=None) as batch_op:
        batch_op.drop_constraint('group_offering_installments_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('group_offering_booking_installments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_offering_booking_installments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_group_offering_booking_installments_status'))
        batch_op.drop_index(batch_op.f('ix_group_offering_booking_installments_booking_id'))

    op.drop_table('group_offering_booking_installments')
    with op.batch_alter_table('group_offering_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_offering_bookings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_group_offering_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_group_offering_bookings_patient_id'))
        batch_op.drop_index(batch_op.f('ix_group_offering_bookings_offering_id'))

    op.drop_table('group_offering_bookings')
    # ### end Alembic commands ###
