"""feature_product_links table

Revision ID: 3f1cefde8fe0
Revises: landfeatprod1
Create Date: 2026-07-28 05:52:32.156656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1cefde8fe0'
down_revision = 'landfeatprod1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_product_links',
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('offering_key', sa.String(length=40), nullable=False),
    sa.Column('plan_ref', sa.String(length=200), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('formula1', sa.Text(), nullable=True),
    sa.Column('formula2', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['doctor_products.product_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('link_id')
    )
    with op.batch_alter_table('feature_product_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_product_links_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index('ix_feature_product_links_offering', ['tenant_id', 'offering_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_product_links_offering_key'), ['offering_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_product_links_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_product_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_product_links_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_feature_product_links_offering_key'))
        batch_op.drop_index('ix_feature_product_links_offering')
        batch_op.drop_index(batch_op.f('ix_feature_product_links_doctor_id'))

    op.drop_table('feature_product_links')
    # ### end Alembic commands ###
