"""credit_policy second_opinion_grants per-type

Revision ID: 544e7dc41084
Revises: a353f578f7f7
Create Date: 2026-08-07 13:32:16.299231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '544e7dc41084'
down_revision = 'a353f578f7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_opinion_grants', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_policies', schema=None) as batch_op:
        batch_op.drop_column('second_opinion_grants')

    # ### end Alembic commands ###
