"""family doctor link + request tables

Revision ID: 58cf7e0f9c59
Revises: cpv1_credit_policy_validity
Create Date: 2026-08-07 06:18:58.996550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Reuse the existing housegrouprequeststatus PG enum — never re-create it.
_HG_STATUS = postgresql.ENUM(
    'PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED',
    name='housegrouprequeststatus', create_type=False,
)


# revision identifiers, used by Alembic.
revision = '58cf7e0f9c59'
down_revision = 'cpv1_credit_policy_validity'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_doctor_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('linked_via', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_doctor_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_doctor_links_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_doctor_links_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_doctor_links_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_doctor_links_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('uq_family_doctor_active_patient', ['tenant_id', 'patient_id'], unique=True, postgresql_where=sa.text('is_active'))

    op.create_table('family_doctor_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('initiated_by', sa.String(length=20), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('target_phone', sa.String(length=20), nullable=True),
    sa.Column('target_name', sa.String(length=200), nullable=True),
    sa.Column('target_last_name', sa.String(length=100), nullable=True),
    sa.Column('invite_code', sa.String(length=40), nullable=True),
    sa.Column('status', _HG_STATUS, nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_doctor_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_doctor_requests_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_doctor_requests_invite_code'), ['invite_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_doctor_requests_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_doctor_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_doctor_requests_target_user_id'), ['target_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_doctor_requests_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_doctor_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_doctor_requests_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_family_doctor_requests_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_family_doctor_requests_status'))
        batch_op.drop_index(batch_op.f('ix_family_doctor_requests_patient_id'))
        batch_op.drop_index(batch_op.f('ix_family_doctor_requests_invite_code'))
        batch_op.drop_index(batch_op.f('ix_family_doctor_requests_doctor_id'))

    op.drop_table('family_doctor_requests')
    with op.batch_alter_table('family_doctor_links', schema=None) as batch_op:
        batch_op.drop_index('uq_family_doctor_active_patient', postgresql_where=sa.text('is_active'))
        batch_op.drop_index(batch_op.f('ix_family_doctor_links_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_family_doctor_links_patient_id'))
        batch_op.drop_index(batch_op.f('ix_family_doctor_links_is_active'))
        batch_op.drop_index(batch_op.f('ix_family_doctor_links_doctor_id'))

    op.drop_table('family_doctor_links')
    # ### end Alembic commands ###
