"""patient family plan quotas policy table

Revision ID: 6167bbe6bd4a
Revises: 6db470d176b4
Create Date: 2026-08-09 10:42:53.120929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6167bbe6bd4a'
down_revision = '6db470d176b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_family_policies',
    sa.Column('patient_family_policy_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('max_minor_subaccounts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_family_links', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_patient_roles', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], name='fk_patient_family_policies_plan_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_family_policy_id'),
    sa.UniqueConstraint('tenant_id', 'plan_id', name='uq_patient_family_policy_plan')
    )
    with op.batch_alter_table('patient_family_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_family_policies_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_family_policies_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_family_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_family_policies_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_patient_family_policies_plan_id'))

    op.drop_table('patient_family_policies')
    # ### end Alembic commands ###
