"""individual product scheduling+tax + order payout ledger

Revision ID: 6226a729f0de
Revises: 81609ca82b56
Create Date: 2026-07-26 07:22:22.570514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6226a729f0de'
down_revision = '81609ca82b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_order_payouts',
    sa.Column('payout_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('doctor_name', sa.String(length=150), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tds_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['marketplace_orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payout_id')
    )
    with op.batch_alter_table('marketplace_order_payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_order_payouts_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_order_payouts_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_order_payouts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_order_payouts_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('doctor_marketplace_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_consultations', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('max_consultations', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('min_call_duration', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('max_call_duration', sa.Integer(), nullable=False, server_default='30'))
        batch_op.add_column(sa.Column('tax_mode', sa.String(length=20), nullable=False, server_default='none'))
        batch_op.add_column(sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('igst_rate', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_marketplace_products', schema=None) as batch_op:
        batch_op.drop_column('igst_rate')
        batch_op.drop_column('sgst_rate')
        batch_op.drop_column('cgst_rate')
        batch_op.drop_column('tax_mode')
        batch_op.drop_column('max_call_duration')
        batch_op.drop_column('min_call_duration')
        batch_op.drop_column('max_consultations')
        batch_op.drop_column('min_consultations')

    with op.batch_alter_table('marketplace_order_payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_order_payouts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_order_payouts_status'))
        batch_op.drop_index(batch_op.f('ix_marketplace_order_payouts_order_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_order_payouts_doctor_id'))

    op.drop_table('marketplace_order_payouts')
    # ### end Alembic commands ###
