"""add tenant_id FKs to new policy/interest tables

Revision ID: 626034020fba
Revises: a7c9e13f5b66
Create Date: 2026-08-06 10:05:06.176455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626034020fba'
down_revision = 'a7c9e13f5b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_policies', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'approval_policies_tenant_id_fkey', 'tenants',
            ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('charge_policies', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'charge_policies_tenant_id_fkey', 'tenants',
            ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('feature_doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_doctors_team'))
        batch_op.create_index(batch_op.f('ix_feature_doctors_team_id'), ['team_id'], unique=False)

    with op.batch_alter_table('pending_doctor_actions', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'pending_doctor_actions_tenant_id_fkey', 'tenants',
            ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('platform_feature_doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_feature_doctors_team'))
        batch_op.create_index(batch_op.f('ix_platform_feature_doctors_team_id'), ['team_id'], unique=False)

    with op.batch_alter_table('service_interests', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'service_interests_tenant_id_fkey', 'tenants',
            ['tenant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_interests', schema=None) as batch_op:
        batch_op.drop_constraint('service_interests_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('platform_feature_doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_feature_doctors_team_id'))
        batch_op.create_index(batch_op.f('ix_platform_feature_doctors_team'), ['team_id'], unique=False)

    with op.batch_alter_table('pending_doctor_actions', schema=None) as batch_op:
        batch_op.drop_constraint('pending_doctor_actions_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('feature_doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_doctors_team_id'))
        batch_op.create_index(batch_op.f('ix_feature_doctors_team'), ['team_id'], unique=False)

    with op.batch_alter_table('charge_policies', schema=None) as batch_op:
        batch_op.drop_constraint('charge_policies_tenant_id_fkey', type_='foreignkey')

    with op.batch_alter_table('approval_policies', schema=None) as batch_op:
        batch_op.drop_constraint('approval_policies_tenant_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###
