"""patient family roles + permissions + member role_id

Revision ID: 6db470d176b4
Revises: 1a543f48bb1a
Create Date: 2026-08-09 10:05:11.140786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db470d176b4'
down_revision = '1a543f48bb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_roles',
    sa.Column('patient_role_id', sa.UUID(), nullable=False),
    sa.Column('owner_patient_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_role_id')
    )
    with op.batch_alter_table('patient_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_roles_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_roles_owner_patient_id'), ['owner_patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_roles_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('uq_patient_role_name', ['tenant_id', 'owner_patient_id', 'name'], unique=True, postgresql_nulls_not_distinct=True, postgresql_where=sa.text('is_deleted = false'))

    op.create_table('patient_role_permissions',
    sa.Column('patient_permission_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('module_key', sa.String(length=120), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_manage', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['patient_roles.patient_role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_permission_id'),
    sa.UniqueConstraint('role_id', 'module_key', name='uq_patient_role_perm')
    )
    with op.batch_alter_table('patient_role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_role_permissions_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_role_permissions_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('house_group_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_house_group_members_role_id'), ['role_id'], unique=False)
        batch_op.create_foreign_key(None, 'patient_roles', ['role_id'], ['patient_role_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house_group_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_house_group_members_role_id'))
        batch_op.drop_column('role_id')

    with op.batch_alter_table('patient_role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_role_permissions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_patient_role_permissions_role_id'))

    op.drop_table('patient_role_permissions')
    with op.batch_alter_table('patient_roles', schema=None) as batch_op:
        batch_op.drop_index('uq_patient_role_name', postgresql_nulls_not_distinct=True, postgresql_where=sa.text('is_deleted = false'))
        batch_op.drop_index(batch_op.f('ix_patient_roles_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_patient_roles_owner_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_roles_is_deleted'))

    op.drop_table('patient_roles')
    # ### end Alembic commands ###
