"""entity_profiles multi-entity with primary

Revision ID: 70a6ac254957
Revises: 626034020fba
Create Date: 2026-08-06 15:30:06.675867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a6ac254957'
down_revision = '626034020fba'
branch_labels = None
depends_on = None


def upgrade():
    # Add is_primary with a temporary server_default so existing rows
    # (currently exactly one entity per owner) become primary, then drop the
    # default to match the model (which declares no server_default).
    op.add_column(
        'entity_profiles',
        sa.Column('is_primary', sa.Boolean(), nullable=False,
                  server_default=sa.text('true')),
    )
    op.alter_column('entity_profiles', 'is_primary', server_default=None)

    with op.batch_alter_table('entity_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_entity_profile_clinic'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_entity_profile_hospital'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_entity_profile_patient'), type_='unique')
        batch_op.create_index(batch_op.f('ix_entity_profiles_is_primary'), ['is_primary'], unique=False)
        batch_op.create_index('uq_entity_primary_clinic', ['tenant_id', 'clinic_id'], unique=True, postgresql_where=sa.text('is_primary AND clinic_id IS NOT NULL'))
        batch_op.create_index('uq_entity_primary_hospital', ['tenant_id', 'hospital_id'], unique=True, postgresql_where=sa.text('is_primary AND hospital_id IS NOT NULL'))
        batch_op.create_index('uq_entity_primary_patient', ['tenant_id', 'patient_id'], unique=True, postgresql_where=sa.text('is_primary AND patient_id IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_profiles', schema=None) as batch_op:
        batch_op.drop_index('uq_entity_primary_patient', postgresql_where=sa.text('is_primary AND patient_id IS NOT NULL'))
        batch_op.drop_index('uq_entity_primary_hospital', postgresql_where=sa.text('is_primary AND hospital_id IS NOT NULL'))
        batch_op.drop_index('uq_entity_primary_clinic', postgresql_where=sa.text('is_primary AND clinic_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_entity_profiles_is_primary'))
        batch_op.create_unique_constraint(batch_op.f('uq_entity_profile_patient'), ['tenant_id', 'patient_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('uq_entity_profile_hospital'), ['tenant_id', 'hospital_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('uq_entity_profile_clinic'), ['tenant_id', 'clinic_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('is_primary')

    # ### end Alembic commands ###
