"""Add is_receiver in plan types

Revision ID: 7579079cc6f0
Revises: 9a2be5a4a60e
Create Date: 2026-07-16 09:59:07.109145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7579079cc6f0'
down_revision = '9a2be5a4a60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saas_plan_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_receiver', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saas_plan_types', schema=None) as batch_op:
        batch_op.drop_column('is_receiver')

    # ### end Alembic commands ###
