"""add can_pay_on_behalf to patient_staff

Revision ID: 7848890d0a34
Revises: ca42db2919a7
Create Date: 2026-08-11 12:00:05.387857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7848890d0a34'
down_revision = 'ca42db2919a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_pay_on_behalf', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_staff', schema=None) as batch_op:
        batch_op.drop_column('can_pay_on_behalf')

    # ### end Alembic commands ###
