"""service communication module

Creates the tables behind communication that is bundled INTO an admin-authored
Service/Product (nutrition package, wellness plan, chronic-disease
management...): a purchase gets its own channel with chat, provider-scheduled
calls, forms, documents, an audit timeline and its own quotas.

All ten tables are tenant-scoped, so RLS is enabled at the end of ``upgrade``
(autogenerate cannot infer policies). Every table is brand new and therefore
empty, so no backfill ordering is needed — unlike the tenant-scoping migrations
this mirrors, RLS can simply go last.

Revision ID: 7efb37d63ab0
Revises: 0389f9e1d9d3
Create Date: 2026-07-20 23:22:27.197643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.models._base import generate_rls_sql

# revision identifiers, used by Alembic.
revision = '7efb37d63ab0'
down_revision = '0389f9e1d9d3'
branch_labels = None
depends_on = None

# Enum types this migration OWNS. They must be dropped on downgrade —
# ``op.drop_table`` leaves the type behind, so without this a
# downgrade→upgrade round-trip fails with DuplicateObject on re-CREATE TYPE.
# ``membershipvertical`` is deliberately absent: it predates this migration
# (see create_type=False on provider_type) and dropping it would break the
# membership tables.
_OWNED_ENUM_TYPES = (
    'purchasedservicestatus',
    'servicechannelstatus',
    'channelparticipantrole',
    'channelmessagekind',
    'scheduledcallmode',
    'scheduledcallstatus',
    'channeldocumentcategory',
    'channeleventtype',
)

# Order matters only for the drop side (children before parents).
_TABLES = (
    'service_communication_configs',
    'purchased_services',
    'service_channels',
    'channel_participants',
    'channel_messages',
    'scheduled_calls',
    'call_sessions',
    'channel_documents',
    'channel_form_responses',
    'channel_events',
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_communication_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('validity_days', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('chat_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('audio_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('video_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('documents_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('forms_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('audio_minutes_quota', sa.Integer(), nullable=True),
    sa.Column('video_minutes_quota', sa.Integer(), nullable=True),
    sa.Column('max_attachment_mb', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('retention_days', sa.Integer(), server_default=sa.text('365'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('(audio_minutes_quota IS NULL) OR (audio_minutes_quota >= 0)', name='ck_service_comm_audio_quota_nonneg'),
    sa.CheckConstraint('(video_minutes_quota IS NULL) OR (video_minutes_quota >= 0)', name='ck_service_comm_video_quota_nonneg'),
    sa.CheckConstraint('max_attachment_mb > 0', name='ck_service_comm_attachment_positive'),
    sa.CheckConstraint('retention_days >= 0', name='ck_service_comm_retention_nonneg'),
    sa.CheckConstraint('validity_days > 0', name='ck_service_comm_validity_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['doctor_products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_communication_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_communication_configs_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_communication_configs_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_communication_configs_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_communication_configs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_service_comm_config_product', ['tenant_id', 'product_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))

    op.create_table('purchased_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    # Reuses the existing ``membershipvertical`` type (created by the
    # membership migrations) — create_type=False stops Alembic re-issuing
    # CREATE TYPE, which fails with DuplicateObject.
    sa.Column('provider_type', postgresql.ENUM(
        'DOCTOR', 'CLINIC', 'HOSPITAL',
        name='membershipvertical', create_type=False,
    ), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'expired', 'cancelled', name='purchasedservicestatus'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('chat_enabled', sa.Boolean(), nullable=False),
    sa.Column('audio_enabled', sa.Boolean(), nullable=False),
    sa.Column('video_enabled', sa.Boolean(), nullable=False),
    sa.Column('documents_enabled', sa.Boolean(), nullable=False),
    sa.Column('forms_enabled', sa.Boolean(), nullable=False),
    sa.Column('audio_minutes_quota', sa.Integer(), nullable=True),
    sa.Column('video_minutes_quota', sa.Integer(), nullable=True),
    sa.Column('max_attachment_mb', sa.Integer(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('audio_minutes_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('video_minutes_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['marketplace_orders.order_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['doctor_products.product_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchased_services', schema=None) as batch_op:
        batch_op.create_index('ix_purchased_services_expiry', ['status', 'valid_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchased_services_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchased_services_order_id'), ['order_id'], unique=False)
        batch_op.create_index('ix_purchased_services_patient', ['tenant_id', 'patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchased_services_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchased_services_product_id'), ['product_id'], unique=False)
        batch_op.create_index('ix_purchased_services_provider', ['tenant_id', 'provider_type', 'provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchased_services_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchased_services_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchased_services_valid_until'), ['valid_until'], unique=False)

    op.create_table('service_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchased_service_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'read_only', 'archived', name='servicechannelstatus'), nullable=False),
    sa.Column('read_only_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchased_service_id'], ['purchased_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_channels_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_channels_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_channels_purchased_service_id'), ['purchased_service_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_channels_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_channels_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('channel_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('patient', 'provider', 'nurse', 'family', 'observer', name='channelparticipantrole'), nullable=False),
    sa.Column('can_send', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['service_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_participants_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_participants_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_participants_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_participants_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ux_channel_participant_user', ['channel_id', 'user_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))

    op.create_table('channel_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_participant_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('uploaded', 'consultation', 'report', name='channeldocumentcategory'), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('s3_bucket', sa.String(length=200), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('s3_region', sa.String(length=50), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['service_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_participant_id'], ['channel_participants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_documents_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_documents_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_documents_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index('ix_channel_documents_listing', ['channel_id', 'category', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_documents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('channel_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('actor_participant_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('service_booked', 'channel_created', 'call_scheduled', 'call_accepted', 'participant_joined', 'call_completed', 'call_cancelled', 'form_submitted', 'document_uploaded', 'service_expired', 'conversation_archived', name='channeleventtype'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_participant_id'], ['channel_participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['service_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_events_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_channel_events_timeline', ['channel_id', 'occurred_at'], unique=False)

    op.create_table('channel_form_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by_participant_id', sa.UUID(), nullable=True),
    sa.Column('form_key', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['service_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_participant_id'], ['channel_participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_form_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_form_responses_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_form_responses_form_key'), ['form_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_form_responses_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_form_responses_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('scheduled_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('created_by_participant_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.Enum('audio', 'video', name='scheduledcallmode'), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'scheduled', 'accepted', 'in_progress', 'completed', 'cancelled', 'no_show', name='scheduledcallstatus'), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('patient_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('twilio_room_sid', sa.String(length=64), nullable=True),
    sa.Column('twilio_room_name', sa.String(length=128), nullable=True),
    sa.Column('connected_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('scheduled_end > scheduled_start', name='ck_scheduled_call_window_valid'),
    sa.ForeignKeyConstraint(['channel_id'], ['service_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_participant_id'], ['channel_participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_calls_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_calls_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_calls_scheduled_start'), ['scheduled_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_calls_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_calls_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_calls_twilio_room_name'), ['twilio_room_name'], unique=False)
        batch_op.create_index('ix_scheduled_calls_upcoming', ['status', 'scheduled_start'], unique=False)

    op.create_table('call_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scheduled_call_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('twilio_participant_sid', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['channel_participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scheduled_call_id'], ['scheduled_calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_sessions_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_sessions_scheduled_call_id'), ['scheduled_call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_sessions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_sessions_twilio_participant_sid'), ['twilio_participant_sid'], unique=False)

    op.create_table('channel_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('sender_participant_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('text', 'attachment', 'proposal', name='channelmessagekind'), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('client_msg_id', sa.String(length=64), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['service_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['channel_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_participant_id'], ['channel_participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_messages_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index('ix_channel_messages_history', ['channel_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_messages_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_messages_sender_participant_id'), ['sender_participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_messages_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_channel_messages_client_id', ['channel_id', 'client_msg_id'], unique=True, postgresql_where=sa.text('client_msg_id IS NOT NULL AND is_deleted = false'))

    # ### end Alembic commands ###

    # Tenant isolation. Autogenerate never emits these, so a table added here
    # without this loop would be cross-tenant readable.
    for table in _TABLES:
        for stmt in generate_rls_sql(table):
            op.execute(stmt)


def downgrade():
    # Policies must go before the tables they guard.
    for table in _TABLES:
        op.execute(f'ALTER TABLE {table} DISABLE ROW LEVEL SECURITY')
        op.execute(f'DROP POLICY IF EXISTS tenant_isolation_{table} ON {table}')
        op.execute(f'DROP POLICY IF EXISTS tenant_insert_{table} ON {table}')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_messages', schema=None) as batch_op:
        batch_op.drop_index('ux_channel_messages_client_id', postgresql_where=sa.text('client_msg_id IS NOT NULL AND is_deleted = false'))
        batch_op.drop_index(batch_op.f('ix_channel_messages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_channel_messages_sender_participant_id'))
        batch_op.drop_index(batch_op.f('ix_channel_messages_is_deleted'))
        batch_op.drop_index('ix_channel_messages_history')
        batch_op.drop_index(batch_op.f('ix_channel_messages_channel_id'))

    op.drop_table('channel_messages')
    with op.batch_alter_table('call_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_sessions_twilio_participant_sid'))
        batch_op.drop_index(batch_op.f('ix_call_sessions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_call_sessions_scheduled_call_id'))
        batch_op.drop_index(batch_op.f('ix_call_sessions_participant_id'))

    op.drop_table('call_sessions')
    with op.batch_alter_table('scheduled_calls', schema=None) as batch_op:
        batch_op.drop_index('ix_scheduled_calls_upcoming')
        batch_op.drop_index(batch_op.f('ix_scheduled_calls_twilio_room_name'))
        batch_op.drop_index(batch_op.f('ix_scheduled_calls_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_calls_status'))
        batch_op.drop_index(batch_op.f('ix_scheduled_calls_scheduled_start'))
        batch_op.drop_index(batch_op.f('ix_scheduled_calls_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_scheduled_calls_channel_id'))

    op.drop_table('scheduled_calls')
    with op.batch_alter_table('channel_form_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_form_responses_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_channel_form_responses_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_channel_form_responses_form_key'))
        batch_op.drop_index(batch_op.f('ix_channel_form_responses_channel_id'))

    op.drop_table('channel_form_responses')
    with op.batch_alter_table('channel_events', schema=None) as batch_op:
        batch_op.drop_index('ix_channel_events_timeline')
        batch_op.drop_index(batch_op.f('ix_channel_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_channel_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_channel_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_channel_events_channel_id'))

    op.drop_table('channel_events')
    with op.batch_alter_table('channel_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_documents_tenant_id'))
        batch_op.drop_index('ix_channel_documents_listing')
        batch_op.drop_index(batch_op.f('ix_channel_documents_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_channel_documents_channel_id'))
        batch_op.drop_index(batch_op.f('ix_channel_documents_category'))

    op.drop_table('channel_documents')
    with op.batch_alter_table('channel_participants', schema=None) as batch_op:
        batch_op.drop_index('ux_channel_participant_user', postgresql_where=sa.text('is_deleted = false'))
        batch_op.drop_index(batch_op.f('ix_channel_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_channel_participants_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_channel_participants_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_channel_participants_channel_id'))

    op.drop_table('channel_participants')
    with op.batch_alter_table('service_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_channels_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_service_channels_status'))
        batch_op.drop_index(batch_op.f('ix_service_channels_purchased_service_id'))
        batch_op.drop_index(batch_op.f('ix_service_channels_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_service_channels_archived_at'))

    op.drop_table('service_channels')
    with op.batch_alter_table('purchased_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchased_services_valid_until'))
        batch_op.drop_index(batch_op.f('ix_purchased_services_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_purchased_services_status'))
        batch_op.drop_index('ix_purchased_services_provider')
        batch_op.drop_index(batch_op.f('ix_purchased_services_product_id'))
        batch_op.drop_index(batch_op.f('ix_purchased_services_patient_id'))
        batch_op.drop_index('ix_purchased_services_patient')
        batch_op.drop_index(batch_op.f('ix_purchased_services_order_id'))
        batch_op.drop_index(batch_op.f('ix_purchased_services_is_deleted'))
        batch_op.drop_index('ix_purchased_services_expiry')

    op.drop_table('purchased_services')
    with op.batch_alter_table('service_communication_configs', schema=None) as batch_op:
        batch_op.drop_index('ux_service_comm_config_product', postgresql_where=sa.text('is_deleted = false'))
        batch_op.drop_index(batch_op.f('ix_service_communication_configs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_service_communication_configs_product_id'))
        batch_op.drop_index(batch_op.f('ix_service_communication_configs_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_service_communication_configs_is_deleted'))

    op.drop_table('service_communication_configs')
    # ### end Alembic commands ###

    # Drop the enum types last — dropping a table does not drop the type it
    # used, and a leftover type makes the next upgrade fail on CREATE TYPE.
    for enum_name in _OWNED_ENUM_TYPES:
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
