"""group offering payout ledger

Revision ID: 81609ca82b56
Revises: 397d99545c6f
Create Date: 2026-07-26 06:49:13.535620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81609ca82b56'
down_revision = '397d99545c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_offering_payouts',
    sa.Column('payout_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('doctor_name', sa.String(length=150), nullable=True),
    sa.Column('qualification_name', sa.String(length=150), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tds_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['group_offering_bookings.booking_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payout_id')
    )
    with op.batch_alter_table('group_offering_payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_offering_payouts_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_payouts_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_payouts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_payouts_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_offering_payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_offering_payouts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_group_offering_payouts_status'))
        batch_op.drop_index(batch_op.f('ix_group_offering_payouts_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_group_offering_payouts_booking_id'))

    op.drop_table('group_offering_payouts')
    # ### end Alembic commands ###
