"""doctorpayout service source + booking team_id

Revision ID: 85a556bd17cb
Revises: ef9cd61ed120
Create Date: 2026-07-26 08:17:21.207778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a556bd17cb'
down_revision = 'ef9cd61ed120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_payouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=30), nullable=False, server_default='appointment'))
        batch_op.add_column(sa.Column('source_ref_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('source_label', sa.String(length=200), nullable=True))
        batch_op.alter_column('appointment_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_doctor_payouts_source_ref_id'), ['source_ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_payouts_source_type'), ['source_type'], unique=False)

    with op.batch_alter_table('group_offering_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_group_offering_bookings_team_id'), ['team_id'], unique=False)
        batch_op.create_foreign_key('group_offering_bookings_team_id_fkey', 'marketplace_service_groups', ['team_id'], ['group_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_offering_bookings', schema=None) as batch_op:
        batch_op.drop_constraint('group_offering_bookings_team_id_fkey', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_group_offering_bookings_team_id'))
        batch_op.drop_column('team_id')

    with op.batch_alter_table('doctor_payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_payouts_source_type'))
        batch_op.drop_index(batch_op.f('ix_doctor_payouts_source_ref_id'))
        batch_op.alter_column('appointment_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('source_label')
        batch_op.drop_column('source_ref_id')
        batch_op.drop_column('source_type')

    # ### end Alembic commands ###
