"""membership subscription disciplinary on_hold

Revision ID: 92dd8ecdb89f
Revises: eeaed1b27699
Create Date: 2026-07-27 08:10:23.241663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92dd8ecdb89f'
down_revision = 'eeaed1b27699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('on_hold', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_subscriptions', schema=None) as batch_op:
        batch_op.drop_column('on_hold')

    # ### end Alembic commands ###
