"""salary payout adjustments audit trail

Revision ID: 955c06d5e5eb
Revises: 0389f9e1d9d3
Create Date: 2026-07-20 23:30:54.405017

Autogenerate chained this off a sibling feature's migration that happened to be
applied to the dev DB at the time; that migration is not part of this change, so
the down_revision is re-pointed to this work's own last migration
(0389f9e1d9d3, the salary lifecycle columns). If both features land on main they
fork from a common parent and a merge revision unifies them there.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955c06d5e5eb'
down_revision = '0389f9e1d9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_payout_adjustments',
    sa.Column('adjustment_id', sa.UUID(), nullable=False),
    sa.Column('salary_payout_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['salary_payout_id'], ['salary_payouts.salary_payout_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('adjustment_id')
    )
    with op.batch_alter_table('salary_payout_adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_payout_adjustments_salary_payout_id'), ['salary_payout_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_payout_adjustments_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_payout_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_payout_adjustments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_salary_payout_adjustments_salary_payout_id'))

    op.drop_table('salary_payout_adjustments')
    # ### end Alembic commands ###
