"""Add icon in plan type

Revision ID: 9a2be5a4a60e
Revises: d347d3df1f1e
Create Date: 2026-07-16 06:37:16.480214

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9a2be5a4a60e"
down_revision = "d347d3df1f1e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("admin_permission_overrides", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admin_overrides_resource_id"))
        batch_op.create_index(
            batch_op.f("ix_admin_permission_overrides_resource_id"), ["resource_id"], unique=False
        )

    with op.batch_alter_table("doctor_billing_profiles", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("doctor_billing_profiles_doctor_id_key"), type_="unique"
        )
        batch_op.drop_index(batch_op.f("ix_doctor_billing_profiles_doctor_id"))
        batch_op.create_index(
            batch_op.f("ix_doctor_billing_profiles_doctor_id"), ["doctor_id"], unique=True
        )

    with op.batch_alter_table("doctor_hospital_affiliations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_doctor_hospital_affiliations_status"), ["status"], unique=False
        )

    with op.batch_alter_table("doctors", schema=None) as batch_op:
        batch_op.alter_column(
            "offered_consultation_types",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=postgresql.JSON(astext_type=sa.Text()),
            existing_nullable=True,
        )

    with op.batch_alter_table("landing_config_snapshots", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "landing_config_snapshots_tenant_id_fkey",
            "tenants",
            ["tenant_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("landing_configs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_landing_configs_status"), ["status"], unique=False)
        batch_op.create_foreign_key(
            "landing_configs_tenant_id_fkey", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("landing_features", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "landing_features_tenant_id_fkey", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("landing_modules", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "landing_modules_tenant_id_fkey", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("notification_templates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_templates_channel"), ["channel"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_templates_is_active"), ["is_active"], unique=False
        )

    with op.batch_alter_table("plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plans_vertical"))
        batch_op.drop_column("vertical")

    with op.batch_alter_table("profile_bank_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pba_cashfree_beneficiary_id"))
        batch_op.create_index(
            batch_op.f("ix_profile_bank_accounts_cashfree_beneficiary_id"),
            ["cashfree_beneficiary_id"],
            unique=False,
        )

    with op.batch_alter_table("saas_plan_types", schema=None) as batch_op:
        batch_op.add_column(sa.Column("icon_key", sa.String(), nullable=True))

    with op.batch_alter_table("tenant_addons", schema=None) as batch_op:
        batch_op.create_index("ix_tenant_addons_tenant", ["tenant_id"], unique=False)

    with op.batch_alter_table("tenant_domain_migration_audit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tdma_tenant_created"))

    with op.batch_alter_table("tenant_provider_subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tps_requested_plan_id"))
        batch_op.create_index(
            batch_op.f("ix_tenant_provider_subscriptions_requested_plan_id"),
            ["requested_plan_id"],
            unique=False,
        )

    with op.batch_alter_table("tenant_subscriptions", schema=None) as batch_op:
        batch_op.create_index("ix_tenant_subscriptions_tenant", ["tenant_id"], unique=False)

    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.alter_column(
            "cf_ownership_verification",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=postgresql.JSON(astext_type=sa.Text()),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "cf_ssl_validation_records",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=postgresql.JSON(astext_type=sa.Text()),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.alter_column(
            "cf_ssl_validation_records",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "cf_ownership_verification",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=True,
        )

    with op.batch_alter_table("tenant_subscriptions", schema=None) as batch_op:
        batch_op.drop_index("ix_tenant_subscriptions_tenant")

    with op.batch_alter_table("tenant_provider_subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenant_provider_subscriptions_requested_plan_id"))
        batch_op.create_index(
            batch_op.f("ix_tps_requested_plan_id"), ["requested_plan_id"], unique=False
        )

    with op.batch_alter_table("tenant_domain_migration_audit", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tdma_tenant_created"),
            ["tenant_id", sa.literal_column("created_at DESC")],
            unique=False,
        )

    with op.batch_alter_table("tenant_addons", schema=None) as batch_op:
        batch_op.drop_index("ix_tenant_addons_tenant")

    with op.batch_alter_table("saas_plan_types", schema=None) as batch_op:
        batch_op.drop_column("icon_key")

    with op.batch_alter_table("profile_bank_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_profile_bank_accounts_cashfree_beneficiary_id"))
        batch_op.create_index(
            batch_op.f("ix_pba_cashfree_beneficiary_id"), ["cashfree_beneficiary_id"], unique=False
        )

    with op.batch_alter_table("plans", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "vertical",
                postgresql.ENUM("DOCTOR", "CLINIC", "HOSPITAL", name="membershipvertical"),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.create_index(batch_op.f("ix_plans_vertical"), ["vertical"], unique=False)

    with op.batch_alter_table("notification_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_templates_is_active"))
        batch_op.drop_index(batch_op.f("ix_notification_templates_channel"))

    with op.batch_alter_table("landing_modules", schema=None) as batch_op:
        batch_op.drop_constraint("landing_modules_tenant_id_fkey", type_="foreignkey")

    with op.batch_alter_table("landing_features", schema=None) as batch_op:
        batch_op.drop_constraint("landing_features_tenant_id_fkey", type_="foreignkey")

    with op.batch_alter_table("landing_configs", schema=None) as batch_op:
        batch_op.drop_constraint("landing_configs_tenant_id_fkey", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_landing_configs_status"))

    with op.batch_alter_table("landing_config_snapshots", schema=None) as batch_op:
        batch_op.drop_constraint("landing_config_snapshots_tenant_id_fkey", type_="foreignkey")

    with op.batch_alter_table("doctors", schema=None) as batch_op:
        batch_op.alter_column(
            "offered_consultation_types",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=True,
        )

    with op.batch_alter_table("doctor_hospital_affiliations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_doctor_hospital_affiliations_status"))

    with op.batch_alter_table("doctor_billing_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_doctor_billing_profiles_doctor_id"))
        batch_op.create_index(
            batch_op.f("ix_doctor_billing_profiles_doctor_id"), ["doctor_id"], unique=False
        )
        batch_op.create_unique_constraint(
            batch_op.f("doctor_billing_profiles_doctor_id_key"),
            ["doctor_id"],
            postgresql_nulls_not_distinct=False,
        )

    with op.batch_alter_table("admin_permission_overrides", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admin_permission_overrides_resource_id"))
        batch_op.create_index(
            batch_op.f("ix_admin_overrides_resource_id"), ["resource_id"], unique=False
        )

    # ### end Alembic commands ###
