"""Add is_popular in feature

Revision ID: 9c3609f12d30
Revises: 1c3a6b40eb08
Create Date: 2026-07-19 10:22:19.043555

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c3609f12d30"
down_revision = "1c3a6b40eb08"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("platform_landing_features", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_popular", sa.Boolean(), nullable=False, server_default=sa.text("false"))
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("platform_landing_features", schema=None) as batch_op:
        batch_op.drop_column("is_popular")

    # ### end Alembic commands ###
