"""Add SAAS Pricing Table

Revision ID: 9d07419c80c2
Revises: 236d70d5180c
Create Date: 2026-07-14 14:04:41.229259

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9d07419c80c2"
down_revision = "236d70d5180c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saas_plan_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("saas_plan_types", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_saas_plan_types_code"), ["code"], unique=True)

    with op.batch_alter_table("plans", schema=None) as batch_op:
        batch_op.add_column(sa.Column("saas_plan_type_id", sa.UUID(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_plans_saas_plan_type_id"), ["saas_plan_type_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_plans_saas_plan_type_id",
            "saas_plan_types",
            ["saas_plan_type_id"],
            ["id"],
            ondelete="RESTRICT",
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plans", schema=None) as batch_op:
        batch_op.drop_constraint("fk_plans_saas_plan_type_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_plans_saas_plan_type_id"))
        batch_op.drop_column("saas_plan_type_id")

    with op.batch_alter_table("saas_plan_types", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saas_plan_types_code"))

    op.drop_table("saas_plan_types")
    # ### end Alembic commands ###
