"""second-opinion credit rate + threshold + per-doctor override

Revision ID: a353f578f7f7
Revises: bdc21c6e5b2f
Create Date: 2026-08-07 09:19:28.038190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a353f578f7f7'
down_revision = 'bdc21c6e5b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_opinion_grant', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('second_opinion_redeem_threshold', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))

    with op.batch_alter_table('doctor_billing_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_opinion_rate_override', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_billing_profiles', schema=None) as batch_op:
        batch_op.drop_column('second_opinion_rate_override')

    with op.batch_alter_table('credit_policies', schema=None) as batch_op:
        batch_op.drop_column('second_opinion_redeem_threshold')
        batch_op.drop_column('second_opinion_grant')

    # ### end Alembic commands ###
