"""Product eligibility criteria + doctor work qualification

Adds the criteria an admin can set on a catalog product (required degrees,
required work qualifications, an experience rule, and a logo), plus the
work-qualification the doctor selects on their About-me profile.

Every criteria column is nullable with no default: NULL/empty means "no rule",
matching the existing allowed_specialization_ids convention, so products that
exist today keep being offerable by anyone.

Hand-written rather than autogenerated: the dev DB is bootstrapped with
create_all(), so `flask db migrate` there diffs against a schema that was never
built by this chain and sweeps in unrelated drift.

Revision ID: b7d41c9e2f60
Revises: e3815f99d212
Create Date: 2026-07-17

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7d41c9e2f60'
down_revision = 'e3815f99d212'
branch_labels = None
depends_on = None


# The enum type already exists (created with profile_about's other status
# columns), so reference it with create_type=False — emitting CREATE TYPE again
# would fail with "type already exists".
_doc_verification_status = postgresql.ENUM(
    'PENDING', 'VERIFIED', 'REJECTED',
    name='documentverificationstatus',
    create_type=False,
)


def upgrade():
    with op.batch_alter_table('doctor_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_degree_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('required_work_qualification_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('experience_rule', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('logo_asset_id', postgresql.UUID(as_uuid=True), nullable=True))
        batch_op.create_foreign_key(
            'fk_doctor_products_logo_asset_id',
            'page_config_assets', ['logo_asset_id'], ['asset_id'],
            ondelete='SET NULL',
        )

    with op.batch_alter_table('profile_about', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_qualification_id', postgresql.UUID(as_uuid=True), nullable=True))
        # server_default so the NOT NULL holds for rows that already exist; the
        # model carries the same default on the Python side.
        batch_op.add_column(sa.Column(
            'work_qualification_verification_status',
            _doc_verification_status,
            nullable=False,
            server_default='PENDING',
        ))
        batch_op.create_index(
            batch_op.f('ix_profile_about_work_qualification_id'),
            ['work_qualification_id'], unique=False,
        )
        batch_op.create_foreign_key(
            'fk_profile_about_work_qualification_id',
            'categories', ['work_qualification_id'], ['category_id'],
            ondelete='SET NULL',
        )


def downgrade():
    with op.batch_alter_table('profile_about', schema=None) as batch_op:
        batch_op.drop_constraint('fk_profile_about_work_qualification_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_profile_about_work_qualification_id'))
        batch_op.drop_column('work_qualification_verification_status')
        batch_op.drop_column('work_qualification_id')

    with op.batch_alter_table('doctor_products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_doctor_products_logo_asset_id', type_='foreignkey')
        batch_op.drop_column('logo_asset_id')
        batch_op.drop_column('experience_rule')
        batch_op.drop_column('required_work_qualification_ids')
        batch_op.drop_column('required_degree_ids')

    # The enum type is shared with profile_about's other status columns —
    # dropping it here would break them.
