"""seller support channel anchor

Revision ID: bcaccfa0008d
Revises: 07e4ec0edfc7
Create Date: 2026-08-21 09:03:40.683314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcaccfa0008d'
down_revision = '07e4ec0edfc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Hand-scoped: the group_offerings/saas_categories drift autogen also
    # proposed is unrelated (same rationale as 658c596259cf).
    with op.batch_alter_table('service_channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('support_seller_tenant_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_service_channels_support_seller_tenant_id'), ['support_seller_tenant_id'], unique=False)
        batch_op.create_index('ux_service_channels_support_per_tenant', ['tenant_id'], unique=True, postgresql_where=sa.text('support_seller_tenant_id IS NOT NULL AND is_deleted = false'))
        batch_op.create_foreign_key('fk_service_channels_support_seller', 'tenants', ['support_seller_tenant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_channels', schema=None) as batch_op:
        batch_op.drop_constraint('fk_service_channels_support_seller', type_='foreignkey')
        batch_op.drop_index('ux_service_channels_support_per_tenant', postgresql_where=sa.text('support_seller_tenant_id IS NOT NULL AND is_deleted = false'))
        batch_op.drop_index(batch_op.f('ix_service_channels_support_seller_tenant_id'))
        batch_op.drop_column('support_seller_tenant_id')

    # ### end Alembic commands ###
