"""service_channel second-opinion (prescription_id + caps)

Revision ID: bdc21c6e5b2f
Revises: 58cf7e0f9c59
Create Date: 2026-08-07 06:42:59.772578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc21c6e5b2f'
down_revision = '58cf7e0f9c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescription_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('max_messages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_call_seconds', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_service_channels_prescription_id'), ['prescription_id'], unique=False)
        batch_op.create_foreign_key(None, 'prescriptions', ['prescription_id'], ['prescription_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_channels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_service_channels_prescription_id'))
        batch_op.drop_column('max_call_seconds')
        batch_op.drop_column('max_messages')
        batch_op.drop_column('prescription_id')

    # ### end Alembic commands ###
