"""plan benefits + child caps + addon quantity

Revision ID: c42ef07eb3ee
Revises: bcaccfa0008d
Create Date: 2026-08-21 09:37:38.335075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c42ef07eb3ee'
down_revision = 'bcaccfa0008d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benefits', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('child_plan_caps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('tenant_addons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_addons', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('child_plan_caps')
        batch_op.drop_column('benefits')

    # ### end Alembic commands ###
