"""Add is_additional in lp

Revision ID: c43e90233131
Revises: d3f7a1b45e29
Create Date: 2026-07-19 06:57:43.863240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c43e90233131'
down_revision = 'd3f7a1b45e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_about', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_prof_about_tenant_owner'), type_='unique')

    with op.batch_alter_table('profile_bank_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_prof_bank_tenant_owner_order'), type_='unique')

    with op.batch_alter_table('profile_declaration_responses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_prof_decl_resp_tenant_owner_config'), type_='unique')

    with op.batch_alter_table('profile_documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_prof_doc_tenant_owner_config'), type_='unique')

    with op.batch_alter_table('profile_education', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_prof_edu_tenant_owner'), type_='unique')

    with op.batch_alter_table('profile_education_degree', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prof_edu_degree_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_prof_edu_degree_profile_owner_id'))
        batch_op.drop_index(batch_op.f('ix_prof_edu_degree_tenant_id'))
        batch_op.create_index(batch_op.f('ix_profile_education_degree_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_education_degree_profile_owner_id'), ['profile_owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_education_degree_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('profile_education_specialization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prof_edu_spec_category_id'))
        batch_op.drop_index(batch_op.f('ix_prof_edu_spec_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_prof_edu_spec_profile_owner_id'))
        batch_op.drop_index(batch_op.f('ix_prof_edu_spec_tenant_id'))
        batch_op.create_index(batch_op.f('ix_profile_education_specialization_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_education_specialization_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_education_specialization_profile_owner_id'), ['profile_owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_education_specialization_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('profile_signatures', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_prof_sig_tenant_owner'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_signatures', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_prof_sig_tenant_owner'), ['tenant_id', 'profile_owner_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('profile_education_specialization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_education_specialization_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_profile_education_specialization_profile_owner_id'))
        batch_op.drop_index(batch_op.f('ix_profile_education_specialization_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_profile_education_specialization_category_id'))
        batch_op.create_index(batch_op.f('ix_prof_edu_spec_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prof_edu_spec_profile_owner_id'), ['profile_owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prof_edu_spec_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prof_edu_spec_category_id'), ['category_id'], unique=False)

    with op.batch_alter_table('profile_education_degree', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_education_degree_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_profile_education_degree_profile_owner_id'))
        batch_op.drop_index(batch_op.f('ix_profile_education_degree_doctor_id'))
        batch_op.create_index(batch_op.f('ix_prof_edu_degree_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prof_edu_degree_profile_owner_id'), ['profile_owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prof_edu_degree_doctor_id'), ['doctor_id'], unique=False)

    with op.batch_alter_table('profile_education', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_prof_edu_tenant_owner'), ['tenant_id', 'profile_owner_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('profile_documents', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_prof_doc_tenant_owner_config'), ['tenant_id', 'profile_owner_id', 'config_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('profile_declaration_responses', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_prof_decl_resp_tenant_owner_config'), ['tenant_id', 'profile_owner_id', 'config_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('profile_bank_accounts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_prof_bank_tenant_owner_order'), ['tenant_id', 'profile_owner_id', 'order_index'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('profile_about', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_prof_about_tenant_owner'), ['tenant_id', 'profile_owner_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
