"""add patient_staff_minor_scopes for caregiver-minor access

Revision ID: ca42db2919a7
Revises: fb4c479f719b
Create Date: 2026-08-11 08:21:23.777213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca42db2919a7'
down_revision = 'fb4c479f719b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_staff_minor_scopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('house_group_member_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('granted_by_id', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['house_group_member_id'], ['house_group_members.member_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['patient_roles.patient_role_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['patient_staff.patient_staff_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'house_group_member_id', name='uq_patient_staff_minor')
    )
    with op.batch_alter_table('patient_staff_minor_scopes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_staff_minor_scopes_house_group_member_id'), ['house_group_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_staff_minor_scopes_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_staff_minor_scopes_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_staff_minor_scopes_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_staff_minor_scopes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_staff_minor_scopes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_patient_staff_minor_scopes_staff_id'))
        batch_op.drop_index(batch_op.f('ix_patient_staff_minor_scopes_role_id'))
        batch_op.drop_index(batch_op.f('ix_patient_staff_minor_scopes_house_group_member_id'))

    op.drop_table('patient_staff_minor_scopes')
    # ### end Alembic commands ###
