"""admin-imposed service tax + consultation on doctor_products

Revision ID: cf55b5b2573a
Revises: ff311d957b77
Create Date: 2026-07-26 09:25:40.650859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf55b5b2573a'
down_revision = 'ff311d957b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_mode', sa.String(length=20), nullable=False, server_default='none'))
        batch_op.add_column(sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('igst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('min_consultations', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('max_consultations', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('voice_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('voice_min_duration', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('voice_max_duration', sa.Integer(), nullable=False, server_default='30'))
        batch_op.add_column(sa.Column('video_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('video_min_duration', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('video_max_duration', sa.Integer(), nullable=False, server_default='30'))
        batch_op.add_column(sa.Column('chat_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_products', schema=None) as batch_op:
        batch_op.drop_column('chat_enabled')
        batch_op.drop_column('video_max_duration')
        batch_op.drop_column('video_min_duration')
        batch_op.drop_column('video_enabled')
        batch_op.drop_column('voice_max_duration')
        batch_op.drop_column('voice_min_duration')
        batch_op.drop_column('voice_enabled')
        batch_op.drop_column('max_consultations')
        batch_op.drop_column('min_consultations')
        batch_op.drop_column('igst_rate')
        batch_op.drop_column('sgst_rate')
        batch_op.drop_column('cgst_rate')
        batch_op.drop_column('tax_mode')

    # ### end Alembic commands ###
