"""Add FAQ in feature

Revision ID: d347d3df1f1e
Revises: 9d07419c80c2
Create Date: 2026-07-16 04:55:21.419302

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d347d3df1f1e"
down_revision = "9d07419c80c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("landing_features", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("faq_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
        )
    with op.batch_alter_table("platform_landing_features", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("faq_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("landing_features", schema=None) as batch_op:
        batch_op.drop_column("faq_json")
    with op.batch_alter_table("platform_landing_features", schema=None) as batch_op:
        batch_op.drop_column("faq_json")

    # ### end Alembic commands ###
