"""provider staff login role and provider-owned roles

Revision ID: d93376d24abd
Revises: 150e59a82b7c
Create Date: 2026-08-06

Two changes, both prerequisites for staff signing in and for a practice
authoring its own roles:

1. ``userrole`` gains PROVIDER_STAFF. Hand-written rather than autogenerated:
   alembic does not diff enum VALUES, so a new member of a Python enum is
   invisible to ``db migrate`` and the first insert fails at runtime instead.
   ADD VALUE also can't run inside a transaction, hence the autocommit block.

2. ``provider_roles`` gains a nullable owner anchor. Null on all three = the
   tenant-wide role an admin curates; set = a role one practice authored for
   itself. Without this, a clinic renaming "Front Desk" or narrowing its
   grants would silently re-scope every other clinic's receptionist in the
   tenant — which is exactly what letting providers edit roles would have
   meant otherwise.

The old unique index is replaced rather than added to: (tenant, type, name)
would now reject a practice's own "Front Desk" because the tenant-wide one
already holds that name. The new one includes the owner columns and is
NULLS NOT DISTINCT so the shared row still collides with itself.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93376d24abd'
down_revision = '150e59a82b7c'
branch_labels = None
depends_on = None


def upgrade():
    # --- 1. the login role ---------------------------------------------------
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'PROVIDER_STAFF'")

    # --- 2. provider-owned roles --------------------------------------------
    op.add_column('provider_roles', sa.Column('owner_doctor_id', sa.UUID(), nullable=True))
    op.add_column('provider_roles', sa.Column('owner_clinic_id', sa.UUID(), nullable=True))
    op.add_column('provider_roles', sa.Column('owner_hospital_id', sa.UUID(), nullable=True))

    op.create_index('ix_provider_roles_owner_doctor_id', 'provider_roles', ['owner_doctor_id'])
    op.create_index('ix_provider_roles_owner_clinic_id', 'provider_roles', ['owner_clinic_id'])
    op.create_index('ix_provider_roles_owner_hospital_id', 'provider_roles', ['owner_hospital_id'])

    op.create_foreign_key('fk_provider_roles_owner_doctor', 'provider_roles',
                          'doctors', ['owner_doctor_id'], ['doctor_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_provider_roles_owner_clinic', 'provider_roles',
                          'clinics', ['owner_clinic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_provider_roles_owner_hospital', 'provider_roles',
                          'hospitals', ['owner_hospital_id'], ['hospital_id'], ondelete='CASCADE')

    op.create_check_constraint(
        'ck_provider_role_one_owner', 'provider_roles',
        'num_nonnulls(owner_doctor_id, owner_clinic_id, owner_hospital_id) <= 1')
    op.create_check_constraint(
        'ck_provider_role_owner_matches_type', 'provider_roles',
        "num_nonnulls(owner_doctor_id, owner_clinic_id, owner_hospital_id) = 0 OR "
        "(provider_type = 'DOCTOR' AND owner_doctor_id IS NOT NULL) OR "
        "(provider_type = 'CLINIC' AND owner_clinic_id IS NOT NULL) OR "
        "(provider_type = 'HOSPITAL' AND owner_hospital_id IS NOT NULL)")

    op.drop_index('uq_provider_role_name', table_name='provider_roles')
    op.create_index(
        'uq_provider_role_name', 'provider_roles',
        ['tenant_id', 'provider_type', 'name',
         'owner_doctor_id', 'owner_clinic_id', 'owner_hospital_id'],
        unique=True, postgresql_nulls_not_distinct=True,
        postgresql_where=sa.text('is_deleted = FALSE'))


def downgrade():
    op.drop_index('uq_provider_role_name', table_name='provider_roles')
    op.create_index('uq_provider_role_name', 'provider_roles',
                    ['tenant_id', 'provider_type', 'name'],
                    unique=True, postgresql_where=sa.text('is_deleted = FALSE'))
    op.drop_constraint('ck_provider_role_owner_matches_type', 'provider_roles', type_='check')
    op.drop_constraint('ck_provider_role_one_owner', 'provider_roles', type_='check')
    for name in ('owner_doctor_id', 'owner_clinic_id', 'owner_hospital_id'):
        op.drop_column('provider_roles', name)
    # PROVIDER_STAFF stays on the enum: Postgres cannot drop a value from an
    # enum type, and any staff User row would still reference it.
