"""Account deletion register + statutory record-identity snapshots.

DPDP Act 2023 erasure meets Indian retention law: when an account is
deleted, the AUTH identity is scrubbed but retained clinical/financial
records must stay identifiable for their statutory retention period
(NMC/MCI Code of Ethics reg. 1.3; Companies Act 2013 s.128(5); CGST Act
s.36; Income-tax rules). Two pieces:

  * ``patients.record_identity`` / ``doctors.record_identity`` — the
    legal identity (name/dob/gender, never contact channels) sealed onto
    the profile row at deletion so records keep rendering the real name.
  * ``account_deletion_records`` — one permanent register row per
    deletion (who / what was scrubbed / why / when + one-way hashes of
    the erased identifiers for dispute lookup).

Hand-written (not autogenerated) so it carries exactly these objects.

Revision ID: delreg1_deletion_register
Revises: targ1_audience_targeting
Create Date: 2026-08-18
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'delreg1_deletion_register'
down_revision = 'targ1_audience_targeting'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        'patients',
        sa.Column('record_identity', sa.JSON(), nullable=True),
    )
    op.add_column(
        'doctors',
        sa.Column('record_identity', sa.JSON(), nullable=True),
    )

    op.create_table(
        'account_deletion_records',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('role', sa.String(length=30), nullable=False),
        sa.Column('email_hash', sa.String(length=64), nullable=True),
        sa.Column('phone_hash', sa.String(length=64), nullable=True),
        sa.Column('identity_snapshot',
                  postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('scrubbed_fields',
                  postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('legal_basis', sa.Text(), nullable=False),
        sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'],
                                ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'],
                                ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_account_deletion_records_tenant_id',
                    'account_deletion_records', ['tenant_id'])
    op.create_index('ix_account_deletion_records_user_id',
                    'account_deletion_records', ['user_id'])
    op.create_index('ix_account_deletion_records_email_hash',
                    'account_deletion_records', ['email_hash'])
    op.create_index('ix_account_deletion_records_phone_hash',
                    'account_deletion_records', ['phone_hash'])


def downgrade():
    op.drop_index('ix_account_deletion_records_phone_hash',
                  table_name='account_deletion_records')
    op.drop_index('ix_account_deletion_records_email_hash',
                  table_name='account_deletion_records')
    op.drop_index('ix_account_deletion_records_user_id',
                  table_name='account_deletion_records')
    op.drop_index('ix_account_deletion_records_tenant_id',
                  table_name='account_deletion_records')
    op.drop_table('account_deletion_records')
    op.drop_column('doctors', 'record_identity')
    op.drop_column('patients', 'record_identity')
