"""Add vertical type

Revision ID: e3815f99d212
Revises: aa11bb22cc33
Create Date: 2026-07-17 10:17:51.697425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3815f99d212'
down_revision = 'aa11bb22cc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vertical_plan_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon_key', sa.String(), nullable=True),
    sa.Column('is_receiver', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vertical_plan_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vertical_plan_types_code'), ['code'], unique=True)

    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benefits', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('vertical_plan_type_id', sa.UUID(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_membership_plans_vertical'))
        batch_op.drop_index(batch_op.f('ix_membership_plans_vertical_tier'), postgresql_where='(is_deleted = false)')
        batch_op.create_index(batch_op.f('ix_membership_plans_vertical_plan_type_id'), ['vertical_plan_type_id'], unique=False)
        batch_op.create_foreign_key('fk_plans_vetical_plan_type_id', 'vertical_plan_types', ['vertical_plan_type_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('price_inr_annual')
        batch_op.drop_column('og_price_inr_monthly')
        batch_op.drop_column('vertical')
        batch_op.drop_column('price_inr_monthly')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('benefits')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benefits', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))

    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_inr_monthly', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vertical', postgresql.ENUM('DOCTOR', 'CLINIC', 'HOSPITAL', name='membershipvertical'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('og_price_inr_monthly', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price_inr_annual', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_plans_vetical_plan_type_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_membership_plans_vertical_plan_type_id'))
        batch_op.create_index(batch_op.f('ix_membership_plans_vertical_tier'), ['vertical', 'tier'], unique=False, postgresql_where='(is_deleted = false)')
        batch_op.create_index(batch_op.f('ix_membership_plans_vertical'), ['vertical'], unique=False)
        batch_op.drop_column('vertical_plan_type_id')
        batch_op.drop_column('benefits')

    with op.batch_alter_table('vertical_plan_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vertical_plan_types_code'))

    op.drop_table('vertical_plan_types')
    # ### end Alembic commands ###
