"""group offering healthcare plan tables

Revision ID: e8af12636f4f
Revises: c4e62a239e10
Create Date: 2026-07-25 14:48:36.429004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8af12636f4f'
down_revision = 'c4e62a239e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_offerings',
    sa.Column('group_offering_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('duration_type', sa.String(length=20), nullable=False),
    sa.Column('duration_value', sa.Integer(), nullable=False),
    sa.Column('patient_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('doctor_budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('group_offering_id')
    )
    with op.batch_alter_table('group_offerings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_offerings_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offerings_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offerings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offerings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('group_offering_members',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('qualification_id', sa.UUID(), nullable=True),
    sa.Column('qualification_name', sa.String(length=150), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('consultation_count', sa.Integer(), nullable=False),
    sa.Column('min_duration', sa.Integer(), nullable=False),
    sa.Column('max_duration', sa.Integer(), nullable=False),
    sa.Column('allocated_budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offering_id'], ['group_offerings.group_offering_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qualification_id'], ['categories.category_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id')
    )
    with op.batch_alter_table('group_offering_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_offering_members_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_members_offering_id'), ['offering_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_members_qualification_id'), ['qualification_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_members_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_offering_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_offering_members_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_group_offering_members_qualification_id'))
        batch_op.drop_index(batch_op.f('ix_group_offering_members_offering_id'))
        batch_op.drop_index(batch_op.f('ix_group_offering_members_doctor_id'))

    op.drop_table('group_offering_members')
    with op.batch_alter_table('group_offerings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_offerings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_group_offerings_status'))
        batch_op.drop_index(batch_op.f('ix_group_offerings_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_group_offerings_is_active'))

    op.drop_table('group_offerings')
    # ### end Alembic commands ###
