"""document-specific disclaimer on prescription template

Revision ID: ec27c29b74c5
Revises: 1b6bdf1de3b1
Create Date: 2026-07-20 09:08:53.758159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec27c29b74c5'
down_revision = '1b6bdf1de3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_disclaimer_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('document_disclaimer_title', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_templates', schema=None) as batch_op:
        batch_op.drop_column('document_disclaimer_title')
        batch_op.drop_column('document_disclaimer_text')

    # ### end Alembic commands ###
