"""group offering slot eligibility (multi qual + experience)

Revision ID: ee6c47624661
Revises: 8459845ef2b1
Create Date: 2026-07-26 12:07:42.153907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee6c47624661'
down_revision = '8459845ef2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_offering_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eligibility', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_offering_members', schema=None) as batch_op:
        batch_op.drop_column('eligibility')

    # ### end Alembic commands ###
