"""membership plan holding_enabled toggle

Revision ID: eeaed1b27699
Revises: 827b023a4f48
Create Date: 2026-07-27 07:26:25.216944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeaed1b27699'
down_revision = '827b023a4f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('holding_enabled', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.drop_column('holding_enabled')

    # ### end Alembic commands ###
