"""group offering teams + per-mode slots + working hours + member installments

Revision ID: ef9cd61ed120
Revises: 6226a729f0de
Create Date: 2026-07-26 08:07:26.694950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9cd61ed120'
down_revision = '6226a729f0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_group_member_installments',
    sa.Column('installment_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('period_label', sa.String(length=60), nullable=True),
    sa.Column('due_after_days', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['marketplace_service_group_members.member_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('installment_id')
    )
    with op.batch_alter_table('service_group_member_installments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_group_member_installments_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_group_member_installments_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('group_offering_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualification_kind', sa.String(length=20), nullable=False, server_default='specialization'))
        batch_op.add_column(sa.Column('min_consultations', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('max_consultations', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('voice_min_duration', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('voice_max_duration', sa.Integer(), nullable=False, server_default='30'))
        batch_op.add_column(sa.Column('video_min_duration', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('video_max_duration', sa.Integer(), nullable=False, server_default='30'))
        batch_op.add_column(sa.Column('chat_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('group_offerings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('working_hours', sa.JSON(), nullable=True))

    with op.batch_alter_table('marketplace_service_group_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_offering_member_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('allocated_fee', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_marketplace_service_group_members_group_offering_member_id'), ['group_offering_member_id'], unique=False)
        batch_op.create_foreign_key('marketplace_service_group_members_group_offering_member_id_fkey', 'group_offering_members', ['group_offering_member_id'], ['member_id'], ondelete='SET NULL')

    with op.batch_alter_table('marketplace_service_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_offering_id', sa.UUID(), nullable=True))
        batch_op.alter_column('product_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_marketplace_service_groups_group_offering_id'), ['group_offering_id'], unique=False)
        batch_op.create_foreign_key('marketplace_service_groups_group_offering_id_fkey', 'group_offerings', ['group_offering_id'], ['group_offering_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_service_groups', schema=None) as batch_op:
        batch_op.drop_constraint('marketplace_service_groups_group_offering_id_fkey', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_marketplace_service_groups_group_offering_id'))
        batch_op.alter_column('product_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('group_offering_id')

    with op.batch_alter_table('marketplace_service_group_members', schema=None) as batch_op:
        batch_op.drop_constraint('marketplace_service_group_members_group_offering_member_id_fkey', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_marketplace_service_group_members_group_offering_member_id'))
        batch_op.drop_column('allocated_fee')
        batch_op.drop_column('group_offering_member_id')

    with op.batch_alter_table('group_offerings', schema=None) as batch_op:
        batch_op.drop_column('working_hours')

    with op.batch_alter_table('group_offering_members', schema=None) as batch_op:
        batch_op.drop_column('chat_enabled')
        batch_op.drop_column('video_max_duration')
        batch_op.drop_column('video_min_duration')
        batch_op.drop_column('voice_max_duration')
        batch_op.drop_column('voice_min_duration')
        batch_op.drop_column('max_consultations')
        batch_op.drop_column('min_consultations')
        batch_op.drop_column('qualification_kind')

    with op.batch_alter_table('service_group_member_installments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_group_member_installments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_service_group_member_installments_member_id'))

    op.drop_table('service_group_member_installments')
    # ### end Alembic commands ###
