"""group offering backing product for channels

Revision ID: f629c0374d80
Revises: ee6c47624661
Create Date: 2026-07-26 12:36:39.584232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f629c0374d80'
down_revision = 'ee6c47624661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_offerings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backing_product_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_group_offerings_backing_product_id'), ['backing_product_id'], unique=False)
        batch_op.create_foreign_key('group_offerings_backing_product_id_fkey', 'doctor_products', ['backing_product_id'], ['product_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_offerings', schema=None) as batch_op:
        batch_op.drop_constraint('group_offerings_backing_product_id_fkey', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_group_offerings_backing_product_id'))
        batch_op.drop_column('backing_product_id')

    # ### end Alembic commands ###
