"""Add legacy plans

Revision ID: f8801ca289cd
Revises: 9c3609f12d30
Create Date: 2026-07-19 14:08:46.339979

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f8801ca289cd"
down_revision = "9c3609f12d30"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("membership_plans", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_legacy", sa.Boolean(), nullable=False, server_default=sa.text("false"))
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("membership_plans", schema=None) as batch_op:
        batch_op.drop_column("is_legacy")

    # ### end Alembic commands ###
