"""feature who_should_join and expected_outcomes

Revision ID: f93fb6c8413d
Revises: tds1perdoc2override
Create Date: 2026-07-25 07:17:53.259476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f93fb6c8413d'
down_revision = 'tds1perdoc2override'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landing_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('who_should_join', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('expected_outcomes', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('platform_landing_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('who_should_join', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('expected_outcomes', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_landing_features', schema=None) as batch_op:
        batch_op.drop_column('expected_outcomes')
        batch_op.drop_column('who_should_join')

    with op.batch_alter_table('landing_features', schema=None) as batch_op:
        batch_op.drop_column('expected_outcomes')
        batch_op.drop_column('who_should_join')

    # ### end Alembic commands ###
