"""optional slot modes + plan booking documents

Revision ID: ff311d957b77
Revises: 3118c02f008a
Create Date: 2026-07-26 09:15:05.161862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff311d957b77'
down_revision = '3118c02f008a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_offering_booking_documents',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('doctor_name', sa.String(length=150), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('document_url', sa.String(length=1000), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('s3_bucket', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['group_offering_bookings.booking_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    with op.batch_alter_table('group_offering_booking_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_offering_booking_documents_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_booking_documents_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_offering_booking_documents_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('group_offering_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('video_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_offering_members', schema=None) as batch_op:
        batch_op.drop_column('video_enabled')
        batch_op.drop_column('voice_enabled')

    with op.batch_alter_table('group_offering_booking_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_offering_booking_documents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_group_offering_booking_documents_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_group_offering_booking_documents_booking_id'))

    op.drop_table('group_offering_booking_documents')
    # ### end Alembic commands ###
