"""patients.invited_by_user_id — track which doctor/admin invited a patient

Round-10 followup. The doctor's "My Patients" page needs to list the
patients the calling doctor invited (with activation status) — mirror
of the hospital admin's ManageDoctors surface. To filter the Patient
table by inviter we need a column that records who created the row
via the invite flow.

Nullable on purpose: every existing Patient row (pre-this-migration)
has unknown provenance, and patients created via the public signup
path have no human inviter at all. ``ON DELETE SET NULL`` keeps the
Patient row alive if the inviting User is later deleted (doctor
churns) — we just lose the "this patient was invited by X" link.

Revision ID: m9h0i1j2k3l4
Revises: l8g9h0i1j2k3
Create Date: 2026-05-24
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


revision = 'm9h0i1j2k3l4'
down_revision = 'l8g9h0i1j2k3'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        'patients',
        sa.Column(
            'invited_by_user_id', UUID(as_uuid=True), nullable=True,
        ),
    )
    op.create_foreign_key(
        'fk_patients_invited_by_user_id',
        'patients', 'users',
        ['invited_by_user_id'], ['user_id'],
        ondelete='SET NULL',
    )
    op.create_index(
        'ix_patients_invited_by_user_id',
        'patients', ['invited_by_user_id'],
    )


def downgrade():
    # Defensive drops: when the bootstrap path uses
    # ``db.create_all() + flask db stamp head`` (CI's empty-DB
    # path + local test envs), the patients table is created by
    # SQLAlchemy at the latest model revision — including this
    # column — without running ``upgrade()``. So the index +
    # constraint may exist under autogenerated names rather than
    # the ones ``upgrade()`` chose. Use IF EXISTS so a stamped-
    # then-downgraded DB doesn't crash with "constraint does
    # not exist" / "index does not exist".
    op.execute(
        'DROP INDEX IF EXISTS ix_patients_invited_by_user_id',
    )
    op.execute(
        'ALTER TABLE patients DROP CONSTRAINT IF EXISTS '
        'fk_patients_invited_by_user_id',
    )
    # The autogenerated FK name SQLAlchemy uses when an explicit
    # ``name=`` isn't pinned in the model. Older test DBs that
    # were stamped before the model gained the explicit name
    # still carry this. Drop it too — IF EXISTS makes it a no-op
    # when the explicit-name drop above already handled it.
    op.execute(
        'ALTER TABLE patients DROP CONSTRAINT IF EXISTS '
        'patients_invited_by_user_id_fkey',
    )
    op.drop_column('patients', 'invited_by_user_id')
