"""media_assets — stable-URL registry over S3 objects

Hand-written (not autogenerated) so local-DB drift from other features
can't leak into the migration. One new table, no changes to existing
tables: the 26 existing ``*_url``/``*_s3_key`` column pairs stay until
their surfaces migrate onto asset rows (backfill script, later phase).

Revision ID: media1_media_assets
Revises: devpush1_device_push_tokens
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = 'media1_media_assets'
down_revision = 'devpush1_device_push_tokens'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'media_assets',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True),
                  sa.ForeignKey('tenants.id'), nullable=True),
        sa.Column('s3_bucket', sa.String(200), nullable=False),
        sa.Column('s3_key', sa.String(500), nullable=False),
        sa.Column('content_type', sa.String(120), nullable=True),
        sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
        sa.Column('sha256', sa.String(64), nullable=True),
        sa.Column('access', sa.String(16), nullable=False,
                  server_default='tenant'),
        sa.Column('asset_type', sa.String(64), nullable=True),
        sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text('now()')),
    )
    op.create_index('ix_media_assets_tenant_id', 'media_assets', ['tenant_id'])
    op.create_index('ix_media_assets_sha256', 'media_assets', ['sha256'])
    op.create_index('ix_media_assets_dedup', 'media_assets',
                    ['tenant_id', 'sha256', 's3_bucket'])


def downgrade():
    op.drop_index('ix_media_assets_dedup', table_name='media_assets')
    op.drop_index('ix_media_assets_sha256', table_name='media_assets')
    op.drop_index('ix_media_assets_tenant_id', table_name='media_assets')
    op.drop_table('media_assets')
