"""Tenant-scope ``vertical_plan_types``.

Promotes the vertical/plan-type taxonomy from a single global table to a
per-tenant, RLS-isolated one — mirroring ``mts1membscope2`` which did the
same for ``membership_plans``.

Why the rows are CLONED rather than just stamped with the default tenant:
these rows drive the public ``/join`` persona picker (via
``/api/public/vertical-plan-types`` → ``useVerticalTypes``) and are the FK
target of ``membership_plans.vertical_plan_type_id``. Assigning them all to
the default tenant would leave every subscriber tenant with zero verticals —
a blank /join page and no way to author a membership plan. So each existing
row is copied into every tenant, and each membership plan is repointed at
its OWN tenant's copy (it may currently point at what becomes another
tenant's row).

Migration steps (populated-table safe):
  1. Add ``tenant_id`` NULLABLE.
  2. Stamp existing rows with the default tenant, then clone the full set
     into every other tenant.
  3. Repoint ``membership_plans.vertical_plan_type_id`` to the same-code row
     owned by that plan's own tenant.
  4. Set ``tenant_id`` NOT NULL + FK + index; swap the global unique on
     ``code`` for a per-tenant unique on ``(tenant_id, code)``.
  5. Enable RLS (LAST, so the backfill above runs unfiltered).

Revision ID: vpt1tenant2scope3
Revises: d91abcfce1e2
Create Date: 2026-07-21
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID

from app.models._base import generate_rls_sql


revision = 'vpt1tenant2scope3'
down_revision = 'd91abcfce1e2'
branch_labels = None
depends_on = None


_DEFAULT_TENANT_SQL = (
    "SELECT id FROM tenants WHERE is_default = true AND is_deleted = false "
    "LIMIT 1"
)


def upgrade():
    conn = op.get_bind()

    op.add_column(
        'vertical_plan_types',
        sa.Column('tenant_id', UUID(as_uuid=True), nullable=True),
    )

    row_count = conn.execute(
        sa.text('SELECT count(*) FROM vertical_plan_types')
    ).scalar()
    default_tenant = conn.execute(sa.text(_DEFAULT_TENANT_SQL)).scalar()

    # Drop the GLOBAL unique on ``code`` up front — the clone step below
    # deliberately repeats each code once per tenant, so it must not be in
    # force while that INSERT runs. The autogenerated name differs by how the
    # column was created (constraint vs unique index), so drop both forms
    # defensively. The per-tenant unique is created after the backfill.
    conn.execute(sa.text(
        'ALTER TABLE vertical_plan_types '
        'DROP CONSTRAINT IF EXISTS vertical_plan_types_code_key'
    ))
    op.execute('DROP INDEX IF EXISTS ix_vertical_plan_types_code')

    # A fresh create_all + stamp bootstrap (CI) has no rows and no seeded
    # tenant — adding NOT NULL to an empty column is fine there.
    if row_count:
        if default_tenant is None:
            raise RuntimeError(
                f'Cannot tenant-scope vertical_plan_types: {row_count} '
                'existing row(s) but no default tenant (Tenant.is_default = '
                'true) to anchor them to.'
            )

        # 1. Anchor the existing (global) rows to the default tenant.
        conn.execute(
            sa.text(
                'UPDATE vertical_plan_types SET tenant_id = :tid '
                'WHERE tenant_id IS NULL'
            ),
            {'tid': str(default_tenant)},
        )

        # 2. Clone that full set into every OTHER tenant, so no tenant is
        #    left without verticals. New ids per row; ``code`` repeats across
        #    tenants, which the new per-tenant unique allows.
        conn.execute(
            sa.text(
                'INSERT INTO vertical_plan_types '
                '  (id, tenant_id, code, name, description, icon_key, '
                '   is_receiver, sort_order) '
                'SELECT gen_random_uuid(), t.id, v.code, v.name, '
                '       v.description, v.icon_key, v.is_receiver, v.sort_order '
                'FROM vertical_plan_types v '
                'CROSS JOIN tenants t '
                'WHERE v.tenant_id = :tid '
                '  AND t.is_deleted = false '
                '  AND t.id <> :tid'
            ),
            {'tid': str(default_tenant)},
        )

        # 3. Repoint each membership plan at its OWN tenant's row. Before
        #    this, a subscriber tenant's plan referenced the (now default-
        #    tenant-owned) global row — a cross-tenant FK.
        conn.execute(sa.text(
            'UPDATE membership_plans mp '
            'SET vertical_plan_type_id = mine.id '
            'FROM vertical_plan_types theirs, vertical_plan_types mine '
            'WHERE mp.vertical_plan_type_id = theirs.id '
            '  AND mine.tenant_id = mp.tenant_id '
            '  AND mine.code = theirs.code '
            '  AND mine.id <> theirs.id'
        ))

    op.alter_column('vertical_plan_types', 'tenant_id', nullable=False)
    op.create_foreign_key(
        'fk_vertical_plan_types_tenant_id', 'vertical_plan_types', 'tenants',
        ['tenant_id'], ['id'], ondelete='CASCADE',
    )
    op.create_index(
        'ix_vertical_plan_types_tenant_id', 'vertical_plan_types',
        ['tenant_id'],
    )

    # 4. Re-create ``code`` as a plain lookup index, plus the per-tenant
    #    unique that replaces the global one dropped above.
    op.create_index(
        'ix_vertical_plan_types_code', 'vertical_plan_types', ['code'],
    )
    op.create_index(
        'ux_vertical_plan_types_tenant_code', 'vertical_plan_types',
        ['tenant_id', 'code'], unique=True,
    )

    # 5. RLS last — the backfill above must run unfiltered.
    for stmt in generate_rls_sql('vertical_plan_types'):
        op.execute(stmt)


def downgrade():
    conn = op.get_bind()
    op.execute('ALTER TABLE vertical_plan_types DISABLE ROW LEVEL SECURITY')
    # generate_rls_sql creates BOTH a USING policy and an INSERT WITH CHECK
    # policy — dropping only the first would leave the table un-writable.
    op.execute(
        'DROP POLICY IF EXISTS tenant_isolation_vertical_plan_types '
        'ON vertical_plan_types'
    )
    op.execute(
        'DROP POLICY IF EXISTS tenant_insert_vertical_plan_types '
        'ON vertical_plan_types'
    )

    default_tenant = conn.execute(sa.text(_DEFAULT_TENANT_SQL)).scalar()
    if default_tenant is not None:
        # Collapse back to one global set: repoint every plan at the
        # default tenant's row, then drop the clones.
        conn.execute(
            sa.text(
                'UPDATE membership_plans mp '
                'SET vertical_plan_type_id = keep.id '
                'FROM vertical_plan_types cur, vertical_plan_types keep '
                'WHERE mp.vertical_plan_type_id = cur.id '
                '  AND keep.tenant_id = :tid '
                '  AND keep.code = cur.code '
                '  AND keep.id <> cur.id'
            ),
            {'tid': str(default_tenant)},
        )
        conn.execute(
            sa.text(
                'DELETE FROM vertical_plan_types WHERE tenant_id <> :tid'
            ),
            {'tid': str(default_tenant)},
        )

    op.drop_index(
        'ux_vertical_plan_types_tenant_code', table_name='vertical_plan_types',
    )
    op.drop_index(
        'ix_vertical_plan_types_tenant_id', table_name='vertical_plan_types',
    )
    op.drop_constraint(
        'fk_vertical_plan_types_tenant_id', 'vertical_plan_types',
        type_='foreignkey',
    )
    op.drop_column('vertical_plan_types', 'tenant_id')
    op.execute('DROP INDEX IF EXISTS ix_vertical_plan_types_code')
    op.create_index(
        'ix_vertical_plan_types_code', 'vertical_plan_types', ['code'],
        unique=True,
    )
